# Generated by Django 5.1.4 on 2026-07-19 16:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_avatar_user_mfa_enabled_user_mfa_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('LOGIN', 'Login'), ('PASSWORD', 'Password'), ('API_KEY', 'API Key'), ('SECURE_NOTE', 'Secure Note'), ('CARD', 'Credit Card'), ('DATABASE', 'Database')], default='LOGIN', max_length=20)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('favorite', models.BooleanField(default=False)),
                ('secret_encrypted', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-favorite', 'title'],
            },
        ),
    ]
