# Generated by Django 5.1.4 on 2026-07-19 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_user_mfa_enabled_user_mfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='memberships',
            field=models.ManyToManyField(blank=True, related_name='members', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The active tenant. Null only for the platform super admin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.tenant'),
        ),
    ]
