# Generated by Django 5.2.4 on 2025-12-23 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('system', 'System'), ('file', 'File')], default='text', max_length=10)),
                ('content', models.TextField()),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meetings.attendee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='meetings.meeting')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
