# Generated by Django 5.2.4 on 2025-12-24 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='is_video_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AudioCallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initiating', 'Initiating'), ('ringing', 'Ringing'), ('connected', 'Connected'), ('on_hold', 'On Hold'), ('ended', 'Ended'), ('failed', 'Failed')], default='initiating', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('audio_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_sessions', to='meetings.attendee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_sessions', to='meetings.meeting')),
            ],
        ),
    ]
