# Generated by Django 5.2.4 on 2025-12-26 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_attendee_is_muted_attendee_is_video_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='is_screen_sharing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MeetingRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('recording', 'Recording'), ('paused', 'Paused'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='starting', max_length=20)),
                ('recording_type', models.CharField(choices=[('audio', 'Audio Only'), ('video', 'Video'), ('screen', 'Screen Share'), ('composite', 'Composite')], default='composite', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_size_mb', models.FloatField(blank=True, null=True)),
                ('s3_bucket', models.CharField(blank=True, max_length=255, null=True)),
                ('s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='meetings.meeting')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_recordings', to='meetings.attendee')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenShareSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='starting', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(default='screen', max_length=50)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_shares', to='meetings.attendee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_shares', to='meetings.meeting')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
