# Generated by Django 5.2.4 on 2026-01-01 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_attendee_is_screen_sharing_meeting_is_recording_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_final', models.BooleanField(default=False)),
                ('speaker_label', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sequence_number', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='meetings.attendee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_captions', to='meetings.meeting')),
            ],
            options={
                'db_table': 'live_caption',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='MeetingTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_transcript', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('language', models.CharField(default='en-US', max_length=10)),
                ('total_words', models.IntegerField(default=0)),
                ('total_speakers', models.IntegerField(default=0)),
                ('s3_bucket', models.CharField(blank=True, max_length=255, null=True)),
                ('s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enable_speaker_identification', models.BooleanField(default=True)),
                ('enable_medical_terminology', models.BooleanField(default=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meeting_transcript',
            },
        ),
        migrations.CreateModel(
            name='TranscriptAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('key_points', models.JSONField(default=list)),
                ('diagnoses_mentioned', models.JSONField(default=list)),
                ('symptoms_mentioned', models.JSONField(default=list)),
                ('medications_mentioned', models.JSONField(default=list)),
                ('procedures_discussed', models.JSONField(default=list)),
                ('action_items', models.JSONField(default=list)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('overall_sentiment', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='meetings.meetingtranscript')),
            ],
            options={
                'db_table': 'transcript_analysis',
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('speaker_label', models.CharField(max_length=50)),
                ('speaker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('duration', models.FloatField()),
                ('confidence', models.FloatField(default=0.0)),
                ('words', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='meetings.meetingtranscript')),
            ],
            options={
                'db_table': 'transcript_segment',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('frequency', models.IntegerField(default=1)),
                ('confidence', models.FloatField(default=0.0)),
                ('timestamps', models.JSONField(default=list)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='meetings.meetingtranscript')),
            ],
            options={
                'db_table': 'meeting_keyword',
                'unique_together': {('transcript', 'keyword')},
            },
        ),
    ]
