# Generated by Django 5.2.4 on 2025-08-28 13:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
        ('trigger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='License',
            new_name='Machine',
        ),
        migrations.AlterModelTable(
            name='machine',
            table='machine',
        ),
    ]
