# Generated by Django 5.2.4 on 2025-09-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_rename_license_machine_alter_machine_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_password',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_username',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
