# Generated by Django 5.2.4 on 2025-09-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_alter_machine_machine_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='license_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='modules_and_apps',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='validity_date',
            field=models.DateTimeField(null=True),
        ),
    ]
