# Generated by Django 5.2.4 on 2025-09-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_alter_machine_license_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='license_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='modules_and_apps',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='validity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
