# Generated by Django 5.2.4 on 2025-09-25 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('agent', models.CharField(blank=True, max_length=150, null=True)),
                ('head_count', models.IntegerField(blank=True, null=True)),
                ('hours_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('operational_model', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_load_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('onsite_head_count', models.IntegerField(blank=True, null=True)),
                ('onsite_hours_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('onsite_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('onsite_additional_load_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('offshore_head_count', models.IntegerField(blank=True, null=True)),
                ('offshore_hours_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offshore_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offshore_additional_load_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
