# Generated by Django 5.2.4 on 2025-09-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processdata',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='processdata',
            table='roi_processdata',
        ),
    ]
