# Generated by Django 5.2.4 on 2025-09-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roi', '0003_processdatas_delete_processdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processdatas',
            old_name='agent_id',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='processdatas',
            old_name='department_id',
            new_name='department',
        ),
    ]
