# Generated by Django 5.2.4 on 2026-01-19 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('mild_moderate', 'Mild to moderate')], max_length=20)),
                ('reactions', models.TextField()),
                ('date_of_onset', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Marked as Error')], default='active', max_length=10)),
                ('reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='tenant_app.patient')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_allergies', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_allergies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=1000)),
                ('reason_for_rx_icd10_code', models.CharField(blank=True, max_length=500, null=True)),
                ('reason_for_rx_icd10_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued'), ('not_administered', 'Not Administered')], default='active', max_length=20)),
                ('patient_instructions', models.TextField(blank=True, help_text='Free-text or built instructions', null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('refills', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('allow_substitution', models.BooleanField(blank=True, default=True, null=True)),
                ('days_supply', models.PositiveIntegerField(blank=True, null=True)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('administered_during_visit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='tenant_app.patient')),
                ('prescriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_written', to='tenant_app.patientprovider')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAllergyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_known_allergies', models.BooleanField(default=False)),
                ('no_known_medication_allergies', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_profile', to='tenant_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_name', models.CharField(max_length=1000)),
                ('snomed_name', models.CharField(max_length=1000)),
                ('icd10_code', models.CharField(max_length=500)),
                ('snomed_code', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('resolved', 'Resolved')], default='active', max_length=10)),
                ('problem_type', models.CharField(blank=True, choices=[('acute', 'Acute'), ('chronic', 'Chronic')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('reconciliation_performed', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problems', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='tenant_app.patient')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('head_circumference_in', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_lbs', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_oz', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature_f', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('spo2', models.PositiveIntegerField(blank=True, null=True)),
                ('inhaled_o2', models.PositiveIntegerField(blank=True, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vitals_entered', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='tenant_app.patient')),
            ],
        ),
    ]
