# Generated by Django 5.2.4 on 2026-01-19 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_notes', '0001_initial'),
        ('tenant_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_type', models.CharField(default='SOAP', max_length=20)),
                ('active_sections', models.JSONField(default=list, help_text='List of enabled sections')),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('sign_off_at', models.DateTimeField(blank=True, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encounter_note', to='tenant_app.appointment')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_notes', to='tenant_app.patientprovider')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounter_notes', to='tenant_app.patient')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes_saved', to=settings.AUTH_USER_MODEL)),
                ('sign_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes_signed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
