# Generated by Django 5.2.4 on 2026-01-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_notes', '0002_clinicalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='sections_notes',
            field=models.JSONField(default=dict),
        ),
    ]
