# Generated by Django 5.1.4 on 2026-07-19 04:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_avatar_user_mfa_enabled_user_mfa_secret'),
        ('connectors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_slug', models.CharField(max_length=60)),
                ('skill_name', models.CharField(max_length=120)),
                ('input', models.JSONField(default=dict)),
                ('output', models.JSONField(default=dict)),
                ('status', models.CharField(default='success', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_runs', to='connectors.connector')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_runs', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
