# Generated by Django 5.1.4 on 2026-07-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillrun',
            name='resolution',
            field=models.CharField(choices=[('OPEN', 'Open'), ('APPROVED', 'Approved'), ('RETRIED', 'Retried'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=12),
        ),
        migrations.AddField(
            model_name='skillrun',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
