import ListLayout from "./Components/ListLayout";

export default function AllPatientsPage() {
  const title = "ALL PATIENT";

  const columns = [
    { accessor_key: "patient_id", title: "Patient ID" },
    { accessor_key: "status", title: "Status" },
    { accessor_key: "patient_name", title: "Patient Name" },
    { accessor_key: "dob", title: "DOB" },
    { accessor_key: "age", title: "Pt Age" },
    { accessor_key: "sex", title: "Sex" },
    { accessor_key: "marital_status", title: "Marital Status" },
    { accessor_key: "email", title: "Email" },
    { accessor_key: "home_phone", title: "Home Phone" },
    { accessor_key: "mobile_phone", title: "Mobile Number" },
    { accessor_key: "address1", title: "Address Line 1" },
  ];

  // No filters shown in screenshot
  const filters = [];

  async function fetchData() {
    return [
      {
        patient_id: 958,
        status: "Active",
        patient_name: "Abamegal, Hildana",
        dob: "06/15/2000",
        age: "25 years",
        sex: "Female",
        marital_status: "Unknown",
        email: "hildana@gmail.com",
        home_phone: "(620) 388-5837",
        mobile_phone: "(620) 388-5837",
        address1: "2515 Burnet Ave",
      },
      {
        patient_id: 2494,
        status: "Active",
        patient_name: "ABBOTT, BRANDON J",
        dob: "09/13/1995",
        age: "30 years",
        sex: "Male",
        marital_status: "Unknown",
        email: "brandonabbott913@gmail.com",
        home_phone: "",
        mobile_phone: "(620) 388-5837",
        address1: "310 N Main St",
      },
      {
        patient_id: 3100,
        status: "Active",
        patient_name: "ABDULRAHMAN, RENAJARETT",
        dob: "09/18/1958",
        age: "67 years",
        sex: "Female",
        marital_status: "Unknown",
        email: "renajarett@yahoo.com",
        home_phone: "(832) 741-9302",
        mobile_phone: "(832) 741-9302",
        address1: "2119 Prairie Field",
      },
      {
        patient_id: 2082,
        status: "Active",
        patient_name: "ABDURRAZAQ, RIDWAN",
        dob: "04/30/2003",
        age: "22 years",
        sex: "Male",
        marital_status: "Unknown",
        email: "rabdurzaq03@gmail.com",
        home_phone: "(410) 262-3786",
        mobile_phone: "(410) 262-3786",
        address1: "5401 W 110th St",
      },
      {
        patient_id: 2466,
        status: "Active",
        patient_name: "ABELL, MICHAEL JEFFREY",
        dob: "05/03/1994",
        age: "31 years",
        sex: "Male",
        marital_status: "Unknown",
        email: "abellmike1@gmail.com",
        home_phone: "(913) 963-2813",
        mobile_phone: "(913) 963-2813",
        address1: "13507 W. 66th Ter",
      },
      {
        patient_id: 3577,
        status: "Active",
        patient_name: "Aberi, Ray",
        dob: "05/14/2018",
        age: "7 years",
        sex: "Male",
        marital_status: "Unknown",
        email: "f_mochama@yahoo.com",
        home_phone: "(316) 217-5274",
        mobile_phone: "(316) 217-5274",
        address1: "5339 N Toben Ct",
      },
      {
        patient_id: 2116,
        status: "Active",
        patient_name: "ABOU FAISSAL, SAMUEL DAD",
        dob: "05/28/2016",
        age: "9 years",
        sex: "Male",
        marital_status: "Divorced",
        email: "faissal@expertautocenter.com",
        home_phone: "(316) 841-1447",
        mobile_phone: "(316) 841-1447",
        address1: "8501 E Killarney",
      },
      {
        patient_id: 937,
        status: "Active",
        patient_name: "ACABAL, OSEAS",
        dob: "08/11/2015",
        age: "10 years",
        sex: "Male",
        marital_status: "Unknown",
        email: "",
        home_phone: "",
        mobile_phone: "",
        address1: "1426 Swaco Ave",
      },
      {
        patient_id: 1937,
        status: "Active",
        patient_name: "ACHEY, RYLEE",
        dob: "09/30/2008",
        age: "17 years",
        sex: "Female",
        marital_status: "Unknown",
        email: "kkachey@hotmail.com",
        home_phone: "(316) 619-4540",
        mobile_phone: "(316) 619-4540",
        address1: "2410 S Canyon St",
      },
      {
        patient_id: 2831,
        status: "Active",
        patient_name: "ACOSTA, MIGUEL ANGEL",
        dob: "09/06/1991",
        age: "34 years",
        sex: "Male",
        marital_status: "Unknown",
        email: "miguidesanrafas@gmail.com",
        home_phone: "(913) 235-0627",
        mobile_phone: "(913) 235-0627",
        address1: "13321 Riverview",
      },
      {
        patient_id: 3083,
        status: "Active",
        patient_name: "ADAMS, ALEXANDRIA T",
        dob: "04/17/1999",
        age: "26 years",
        sex: "Female",
        marital_status: "Unknown",
        email: "adamsalexandria35@yahoo.com",
        home_phone: "(913) 713-5178",
        mobile_phone: "(913) 713-5178",
        address1: "2316 Birch Dr Apt C",
      },
      {
        patient_id: 2750,
        status: "Active",
        patient_name: "ADAMS, CALYBER",
        dob: "11/21/2016",
        age: "9 years",
        sex: "Male",
        marital_status: "Unknown",
        email: "ember.denae11@gmail.com",
        home_phone: "",
        mobile_phone: "(620) 639-2247",
        address1: "2825 Meadow Dr",
      },
      {
        patient_id: 2751,
        status: "Active",
        patient_name: "ADAMS, DYNNVER",
        dob: "11/21/2016",
        age: "9 years",
        sex: "Male",
        marital_status: "Unknown",
        email: "ember.denae11@gmail.com",
        home_phone: "",
        mobile_phone: "(620) 639-2247",
        address1: "2825 Meadow Dr",
      },
      {
        patient_id: 980,
        status: "Active",
        patient_name: "ADAMS, RACHEL",
        dob: "05/19/1995",
        age: "30 years",
        sex: "Female",
        marital_status: "Unknown",
        email: "",
        home_phone: "(316) 640-0135",
        mobile_phone: "(316) 640-0135",
        address1: "2214 S Minneapolis",
      },
    ];
  }

  return (
    <ListLayout
      title={title}
      data={fetchData}
      columns={columns}
      filters={filters}
    />
  );
}
