import ListLayout from "./Components/ListLayout";

export default function InsuranceCollectionsPage() {
  const title = "BILLING INSURANCE COLLECTIONS";

  // These columns only affect the header in ListLayout.
  // Actual row rendering is done by your Table.jsx custom block.
  const columns = [
    { accessor_key: "encounter_id", title: "Encounter ID" },
    { accessor_key: "claim_id", title: "Claim ID" },
    { accessor_key: "date", title: "Date of Service" },
    { accessor_key: "patient", title: "Patient" },
    { accessor_key: "dob", title: "DOB" },
    { accessor_key: "provider", title: "Provider" },
    { accessor_key: "procedure_code", title: "Procedure Code" },
    { accessor_key: "first_billed", title: "First Billed Date" },
    { accessor_key: "modifiers", title: "Modifiers" },
    { accessor_key: "units", title: "Units" },
    { accessor_key: "total_charge", title: "Total Charge" },
    { accessor_key: "insurance", title: "Insurance" },
  ];

  const filters = []; // No filters in screenshot

  async function fetchData() {
    return [
      {
        encounter_id: 2797,
        claim_id: 2884,
        date: "02/25/2024",
        patient: "Clayton Lee Yohn",
        dob: "06/27/2013",
        provider: "MUTHUKUMAR VELLIAN",
        procedure_code: "99213",
        first_billed: "03/12/2024",
        modifiers: "",
        units: 1,
        total_charge: "$150.00",
        insurance: "Blue Cross",
        amount: "$150.00",
        procedures: 1,
        payer: "Blue Cross",
        status: "#00AEEF",
      },
      {
        encounter_id: 2971,
        claim_id: 3063,
        date: "04/03/2024",
        patient: "ELLA MARIE WEMMER",
        dob: "12/24/2015",
        provider: "MUTHUKUMAR VELLIAN",
        procedure_code: "99213",
        first_billed: "04/08/2024",
        modifiers: "",
        units: 1,
        total_charge: "$150.00",
        insurance: "Blue Cross",
        amount: "$150.00",
        procedures: 1,
        payer: "Blue Cross",
        status: "#00AEEF",
      },
      {
        encounter_id: 3095,
        claim_id: 3164,
        date: "04/23/2024",
        patient: "Kinley Curtis",
        dob: "05/01/2011",
        provider: "SHELBY R BROOKS",
        procedure_code: "99214",
        first_billed: "04/29/2024",
        modifiers: "",
        units: 1,
        total_charge: "$170.00",
        insurance: "Blue Shield",
        amount: "$170.00",
        procedures: 1,
        payer: "Blue Shield",
        status: "#00AEEF",
      },
      {
        encounter_id: 3096,
        claim_id: 3174,
        date: "04/23/2024",
        patient: "Thomas Curtis",
        dob: "11/06/2012",
        provider: "SHELBY R BROOKS",
        procedure_code: "99214",
        first_billed: "04/29/2024",
        modifiers: "",
        units: 1,
        total_charge: "$170.00",
        insurance: "Blue Shield",
        amount: "$170.00",
        procedures: 1,
        payer: "Blue Shield",
        status: "#00AEEF",
      },
      {
        encounter_id: 3246,
        claim_id: 3352,
        date: "05/25/2024",
        patient: "Clayton Lee Yohn",
        dob: "06/27/2013",
        provider: "MUTHUKUMAR VELLIAN",
        procedure_code: "99213",
        first_billed: "05/30/2024",
        modifiers: "",
        units: 1,
        total_charge: "$150.00",
        insurance: "Blue Cross",
        amount: "$150.00",
        procedures: 1,
        payer: "Blue Cross",
        status: "#00AEEF",
      },
      {
        encounter_id: 3349,
        claim_id: 3463,
        date: "06/18/2024",
        patient: "Arlo Mccray-Munroe",
        dob: "09/19/2023",
        provider: "MUTHUKUMAR VELLIAN",
        procedure_code: "99252",
        first_billed: "06/26/2024",
        modifiers: "",
        units: 1,
        total_charge: "$300.00",
        insurance: "United",
        amount: "$300.00",
        procedures: 1,
        payer: "United",
        status: "#00AEEF",
      },
      {
        encounter_id: 3349,
        claim_id: 3464,
        date: "06/18/2024",
        patient: "Arlo Mccray-Munroe",
        dob: "09/19/2023",
        provider: "MUTHUKUMAR VELLIAN",
        procedure_code: "99157",
        first_billed: "06/26/2024",
        modifiers: "",
        units: 2,
        total_charge: "$600.00",
        insurance: "United",
        amount: "$600.00",
        procedures: 2,
        payer: "United",
        status: "#00AEEF",
      },
      {
        encounter_id: 3349,
        claim_id: 3465,
        date: "06/18/2024",
        patient: "Arlo Mccray-Munroe",
        dob: "09/19/2023",
        provider: "MUTHUKUMAR VELLIAN",
        procedure_code: "99155",
        first_billed: "06/26/2024",
        modifiers: "",
        units: 1,
        total_charge: "$400.00",
        insurance: "United",
        amount: "$400.00",
        procedures: 1,
        payer: "United",
        status: "#00AEEF",
      },
      {
        encounter_id: 3405,
        claim_id: 3787,
        date: "05/12/2024",
        patient: "MELISSA LAGRIMINI",
        dob: "06/09/1975",
        provider: "CAREY WETTSTEIN",
        procedure_code: "99203",
        first_billed: "08/29/2024",
        modifiers: "",
        units: 1,
        total_charge: "$150.00",
        insurance: "Blue Cross",
        amount: "$150.00",
        procedures: 1,
        payer: "Blue Cross",
        status: "#00AEEF",
      },
      {
        encounter_id: 3445,
        claim_id: 3788,
        date: "07/05/2024",
        patient: "MELISSA LAGRIMINI",
        dob: "06/09/1975",
        provider: "CAREY WETTSTEIN",
        procedure_code: "99213",
        first_billed: "08/29/2024",
        modifiers: "",
        units: 1,
        total_charge: "$150.00",
        insurance: "Blue Cross",
        amount: "$150.00",
        procedures: 1,
        payer: "Blue Cross",
        status: "#00AEEF",
      },
      {
        encounter_id: 3360,
        claim_id: 3822,
        date: "06/19/2024",
        patient: "ELIAS RODRIGUEZ",
        dob: "12/10/2022",
        provider: "MUTHUKUMAR VELLIAN",
        procedure_code: "99252",
        first_billed: "08/30/2024",
        modifiers: "",
        units: 1,
        total_charge: "$300.00",
        insurance: "Sunfire",
        amount: "$300.00",
        procedures: 1,
        payer: "Sunfire",
        status: "#00AEEF",
      },
      {
        encounter_id: 3360,
        claim_id: 3823,
        date: "06/19/2024",
        patient: "ELIAS RODRIGUEZ",
        dob: "12/10/2022",
        provider: "MUTHUKUMAR VELLIAN",
        procedure_code: "99155",
        first_billed: "08/30/2024",
        modifiers: "",
        units: 1,
        total_charge: "$400.00",
        insurance: "Sunfire",
        amount: "$400.00",
        procedures: 1,
        payer: "Sunfire",
        status: "#00AEEF",
      },
      {
        encounter_id: 3360,
        claim_id: 3824,
        date: "06/19/2024",
        patient: "ELIAS RODRIGUEZ",
        dob: "12/10/2022",
        provider: "MUTHUKUMAR VELLIAN",
        procedure_code: "99157",
        first_billed: "08/30/2024",
        modifiers: "",
        units: 1,
        total_charge: "$300.00",
        insurance: "Sunfire",
        amount: "$300.00",
        procedures: 1,
        payer: "Sunfire",
        status: "#00AEEF",
      },
      {
        encounter_id: 3817,
        claim_id: 3964,
        date: "08/13/2024",
        patient: "LAYTON GOODMAN",
        dob: "05/28/2011",
        provider: "MUTHUKUMAR VELLIAN",
        procedure_code: "99214",
        first_billed: "09/20/2024",
        modifiers: "",
        units: 1,
        total_charge: "$170.00",
        insurance: "Blue Cross",
        amount: "$170.00",
        procedures: 1,
        payer: "Blue Cross",
        status: "#00AEEF",
      },
    ];
  }

  return (
    <ListLayout
      title={title}
      data={fetchData}
      columns={columns}
      filters={filters}
    />
  );
}
