# Generated by Django 5.2.4 on 2025-10-11 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, unique=True)),
                ('version_number', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deployed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'version_control',
                'ordering': ['-release_date'],
            },
        ),
    ]
