# Generated by Django 5.2.4 on 2025-08-26 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDetails',
            fields=[
                ('asset_id', models.AutoField(db_column='asset_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='asset_name', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='asset_desc', null=True)),
                ('value', models.TextField(blank=True, db_column='asset_value', null=True)),
                ('asset_type', models.CharField(blank=True, db_column='asset_type', max_length=100, null=True)),
                ('label', models.CharField(blank=True, db_column='asset_label', max_length=100, null=True)),
                ('created_at', models.DateField(blank=True, db_column='asset_created_at', null=True)),
                ('user', models.ForeignKey(blank=True, db_column='asset_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
