# Generated by Django 5.2.4 on 2025-09-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
