# Generated by Django 5.2.4 on 2025-09-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_assetdetails_updated_at_project_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='python_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
