# Generated by Django 5.2.4 on 2025-10-31 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_app_hide_app'),
        ('projects', '0004_task_python_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='apikey',
            field=models.ForeignKey(blank=True, db_column='apikey', null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.generatedapi', to_field='api_key'),
        ),
    ]
