# Generated by Django 5.1.4 on 2026-07-19 01:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('BASIC', 'Basic'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('default_seats', models.PositiveIntegerField(default=5)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('features', models.JSONField(blank=True, default=list)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveIntegerField(default=1, help_text='Number of user seats this license grants.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=12)),
                ('starts_on', models.DateField(default=django.utils.timezone.now)),
                ('expires_on', models.DateField(blank=True, help_text='Leave blank for a perpetual license.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('allocated_by', models.ForeignKey(blank=True, help_text='The super admin who issued this license.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_licenses', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='accounts.tenant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='licensing.licenseplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
