# Generated by Django 5.1.4 on 2026-07-19 01:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='starts_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
