# Generated by Django 5.2.4 on 2026-01-19 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_app', '0001_initial'),
        ('tenant_encounter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(max_length=50, unique=True)),
                ('claim_type', models.CharField(choices=[('837P', 'Professional'), ('837I', 'Institutional')], default='837P', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('All Claims', 'All Claims'), ('Ready to Print Paper', 'Ready to Print Paper'), ('Ready to Electronic Statements', 'Ready to Electronic Statements'), ('Rejections', 'Rejections'), ('Denials', 'Denials'), ('No Response', 'No Response'), ('Pending Insurance', 'Pending Insurance'), ('Pending Patients', 'Pending Patients'), ('Completed', 'Completed')], default='draft', max_length=30)),
                ('total_charge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('payer_claim_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_claim', to='tenant_encounter.encounter')),
            ],
            options={
                'db_table': 'claim',
            },
        ),
        migrations.CreateModel(
            name='ClaimServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_code', models.CharField(max_length=10)),
                ('modifiers', models.CharField(blank=True, max_length=255)),
                ('units', models.PositiveIntegerField()),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diagnosis_pointers', models.CharField(max_length=255)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_claim_submission.claim')),
                ('rendering_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant_app.patientprovider')),
            ],
            options={
                'db_table': 'claim_service_line',
            },
        ),
    ]
