# Generated by Django 5.2.4 on 2026-01-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_claim_submission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('test', 'Test')], max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=22)),
                ('auth_type', models.CharField(choices=[('ssh', 'SSH Key'), ('password', 'Password')], max_length=20)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('ssh_key', models.TextField(blank=True, null=True)),
                ('inbound_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('archive_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('retention_days', models.PositiveIntegerField(blank=True, null=True)),
                ('x12_version', models.CharField(default='005010X221A1', max_length=50)),
                ('compression', models.CharField(choices=[('none', 'None'), ('zip', 'ZIP'), ('gzip', 'GZIP')], default='none', max_length=20)),
                ('naming_convention', models.CharField(blank=True, max_length=255, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('trading_partner_id', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('hourly', 'Hourly'), ('minutes', 'Minutes')], max_length=20)),
                ('delivery_window', models.CharField(blank=True, max_length=100, null=True)),
                ('avg_files_per_day', models.CharField(blank=True, max_length=50, null=True)),
                ('file_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('whitelisted_ips', models.TextField(blank=True, null=True)),
                ('tech_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('ops_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
