# Generated by Django 5.2.4 on 2026-01-25 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_claim_submission', '0003_claim_charge_amount_claim_date_from_claim_date_to_and_more'),
        ('tenant_encounter', '0004_alter_encounter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='tenant_encounter.encounter'),
        ),
    ]
