# Generated by Django 5.1.15 on 2026-01-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_claim_submission', '0004_alter_claim_encounter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='total_charge',
            new_name='allowed',
        ),
        migrations.AddField(
            model_name='claim',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=12),
            preserve_default=False,
        ),
    ]
