import {
  Shield,
  FileText,
  Users,
  Clock,
  DollarSign,
  AlertCircle,
  CreditCard,
  FileCheck,
  Receipt,
  Building,
  UserCheck,
  Banknote,
  Timer,
  TrendingUp,
  Lock,
  ReceiptText,
  IdCard,
  CircleUser,
  ChartNoAxesCombined,
  CircleDollarSign,
  CirclePlus,
  Grid2x2,
  Settings,
  HeartPulse,
} from "lucide-react";

import { BsCollection } from "react-icons/bs";
import { TbFolderDollar } from "react-icons/tb";
import ABALogo from "../assets/logo/ABA.png";
import TranscribeLogo from "../assets/logo/transcribe.png";
import {
  RiAddLine,
  RiAdminLine,
  RiAppsLine,
  RiBarChart2Fill,
  RiCalendarLine,
  RiChatVoiceAiLine,
  RiEyeLine,
  RiFile4Line,
  RiFileTextLine,
  RiFolderLine,
  RiHeartPulseLine,
  RiLogoutBoxLine,
  RiMessageLine,
  RiMic2AiFill,
  RiMoneyDollarCircleLine,
  RiServiceLine,
  RiSettings2Line,
  RiUserAddLine,
  RiVoiceRecognitionLine,
} from "react-icons/ri";
import { DollarSignIcon } from "lucide-react";
import { UtilityPole } from "lucide-react";
import { ToolCaseIcon } from "lucide-react";
import { FaPlus } from "react-icons/fa";
import { IoGridOutline } from "react-icons/io5";
import { NotepadText } from "lucide-react";

const colorClasses = [
  "bg-green-600",
  "bg-red-600",
  "bg-blue-400",
  "bg-purple-700",
  "bg-orange-600",
  "bg-gray-700",
  "bg-red-500",
  "bg-blue-500",
  "bg-purple-500",
  "bg-orange-500",
];

export const agentCategories = [
  {
    title: "AI Role and AI Models",
    agents: [
      // {
      //   name: "ABA",
      //   icon: ABALogo,
      //   image: true,
      //   color: colorClasses[8],
      //   bgColor: "bg-red-500/20",
      //   url: "/aba",
      // },
      {
        name: "Transcribe",
        icon: RiChatVoiceAiLine,
        color: colorClasses[9],
        bgColor: "bg-red-500/20",
        image: true,
        url: "/referral_agent",
      },
      {
        name: "Insurance Verification",
        icon: Shield,
        color: colorClasses[0],
        bgColor: "bg-green-700",
        url: "/insurance_verification",
      },
      {
        name: "Claims Processing",
        icon: FileText,
        color: colorClasses[1],
        bgColor: "bg-red-600/20",
        url: "/claims_processing",
      },
      {
        name: "Prior Authorization",
        icon: FileCheck,
        color: colorClasses[2],
        bgColor: "bg-red-500/20",
        url: "/referral_agent",
      },
      {
        name: "Claims Status",
        icon: Clock,
        color: colorClasses[3],
        bgColor: "bg-blue-300/20",
        url: "/referral_agent",
      },
      {
        name: "Referral",
        icon: Users,
        color: colorClasses[4],
        bgColor: "bg-blue-400/20",
        url: "/referral_agent",
      },
      {
        name: "Intake",
        icon: FileText,
        color: colorClasses[5],
        bgColor: "bg-purple-500/20",
        url: "/referral_agent",
      },
      {
        name: "Denials Management",
        icon: AlertCircle,
        color: colorClasses[6],
        bgColor: "bg-red-500/20",
        url: "/referral_agent",
      },
      {
        name: "EOB to ERA",
        icon: TrendingUp,
        color: colorClasses[7],
        bgColor: "bg-gray-700/20",
        url: "/referral_agent",
      },
      {
        name: "Credit Posting",
        icon: Receipt,
        color: colorClasses[8],
        bgColor: "bg-orange-500/20",
      },
      {
        name: "Payment Posting",
        icon: DollarSign,
        color: colorClasses[9],
        bgColor: "bg-green-500/20",
      },
      {
        name: "Collections",
        icon: BsCollection,
        color: colorClasses[0],
        bgColor: "bg-green-500/20",
      },
      {
        name: "Payment Reminders",
        icon: Clock,
        color: colorClasses[1],
        bgColor: "bg-green-500/20",
      },
      {
        name: "Invoice Processing",
        icon: ReceiptText,
        color: colorClasses[2],
        bgColor: "bg-red-500/20",
      },
      {
        name: "Accounts Receivable",
        icon: TbFolderDollar,
        color: colorClasses[3],
        bgColor: "bg-red-500/20",
      },
      {
        name: "Accounts Payable",
        icon: Receipt,
        color: colorClasses[4],
        bgColor: "bg-orange-500/20",
      },
      {
        name: "Compliance",
        icon: Lock,
        color: colorClasses[5],
        bgColor: "bg-orange-500/20",
      },
      {
        name: "App 1",
        icon: FileText,
        color: colorClasses[6],
        bgColor: "bg-purple-500/20",
      },
      {
        name: "App 2",
        icon: DollarSign,
        color: colorClasses[7],
        bgColor: "bg-green-500/20",
      },
    ],
  },
  // ...existing code...
];

export const agentApps = {
  patient_intake: [
    {
      name: "Fees Schedules",
      id: "fees_schedules",
      icon: Shield,
      url: "/patient_intake/fees_schedules",
    },
    {
      name: "Credentialing",
      id: "credentialing",
      icon: Shield,
      url: "/patient_intake/credentialing",
    },
    {
      name: "EDI/ERA Enrollment",
      id: "edi_era_enrollment",
      icon: Shield,
      url: "/patient_intake/edi_era_enrollment",
    },
    {
      name: "Referrals",
      icon: Shield,
      url: "/patient_intake/referrals",
      id: "referrals",
    },
    {
      name: "Docusign",
      icon: Shield,
      url: "/patient_intake/docusign",
      id: "docusign",
    },
  ],
  scheduling_registration: [
    {
      name: "Scheduling & Registration",
      icon: Shield,
      url: "/scheduling_registration/scheduling_registration",
      id: "scheduling_registration",
    },
    {
      name: "Appointment Reminders",
      icon: Shield,
      url: "/scheduling_registration/appointment_reminders",
      id: "appointment_reminders",
    },
    {
      name: "Insurance Eligibility Checks",
      icon: Shield,
      url: "/scheduling_registration/insurance_eligibility_checks",
      id: "insurance_eligibility_checks",
    },
    {
      name: "Prior Auth",
      icon: Shield,
      url: "/scheduling_registration/prior_auth",
      id: "prior_auth",
    },
  ],

  charges_entries: [
    {
      name: "Patient Check-in",
      icon: Shield,
      url: "/charges_entries/patient_checkin",
      id: "patient_checkin",
    },
    {
      name: "Co-pay & Deductibles",
      icon: Shield,
      url: "/charges_entries/copay_deductibles",
      id: "copay_deductibles",
    },
    {
      name: "Coding & Charge Capture",
      icon: Shield,
      url: "/charges_entries/coding_charge_capture",
      id: "coding_charge_capture",
    },
    {
      name: "Charges Entry",
      icon: Shield,
      url: "/charges_entries/charges_entry",
      id: "charges_entry",
    },
  ],

  claims: [
    {
      name: "Claim Submissions",
      icon: Shield,
      url: "/claims/claim_submissions",
      id: "claim_submissions",
    },
    {
      name: "Claim Status Monitoring",
      icon: Shield,
      url: "/claims/claim_status_monitoring",
      id: "claim_status_monitoring",
    },
    {
      name: "EDI Management",
      icon: Shield,
      url: "/claims/edi_management",
      id: "edi_management",
    },
    {
      name: "Claim Intake",
      icon: Shield,
      url: "/claims/claim_intake",
      id: "claim_intake",
    },
    {
      name: "Adjudication",
      icon: Shield,
      url: "/claims/adjudication",
      id: "adjudication",
    },
    { name: "Custom", icon: Shield, url: null, id: null },
  ],
  denials: [
    {
      name: "Denial Analysis",
      icon: Shield,
      url: "/denials/denial_analysis",
      id: "denial_analysis",
    },
    {
      name: "Appeals and Resolution",
      icon: Shield,
      url: "/denials/appeals_resolution",
      id: "appeals_resolution",
    },
    {
      name: "Request for Information",
      icon: Shield,
      url: "/denials/request_for_information",
      id: "request_for_information",
    },
    {
      name: "Plan Enrollment",
      icon: Shield,
      url: "/denials/plan_enrollment",
      id: "plan_enrollment",
    },
    { name: "Custom", icon: Shield, url: null },
  ],

  payments: [
    {
      name: "Payment Posting",
      icon: Shield,
      url: "/payments/payment_posting",
      id: "payment_posting",
    },
    {
      name: "Cash Reconciliation",
      icon: Shield,
      url: "/payments/cash_reconciliation",
      id: "cash_reconciliation",
    },
    {
      name: "Accounts Payable",
      icon: Shield,
      url: "/payments/accounts_payable",
      id: "accounts_payable",
    },
    {
      name: "AR Notification",
      icon: Shield,
      url: "/payments/ar_notification",
      id: "ar_notification",
    },
    {
      name: "Mail Processing",
      icon: Shield,
      url: "/payments/mail_processing",
      id: "mail_processing",
    },
    {
      name: "Scanning & Indexing",
      icon: Shield,
      url: "/payments/scanning_indexing",
      id: "scanning_indexing",
    },
    {
      name: "ERA/EFT Processing",
      icon: Shield,
      url: "/payments/era_eft_processing",
      id: "era_eft_processing",
    },
    { name: "Custom", icon: Shield, url: null, id: null },
  ],

  patient_services: [
    {
      name: "Patient Statements",
      icon: Shield,
      url: "/patient_services/patient_statements",
      id: "patient_statements",
    },
    {
      name: "Payment Reminders",
      icon: Shield,
      url: "/patient_services/payment_reminders",
      id: "payment_reminders",
    },
    {
      name: "Patient Refunds",
      icon: Shield,
      url: "/patient_services/patient_refunds",
      id: "patient_refunds",
    },
    {
      name: "Transition to Collections",
      icon: Shield,
      url: "/patient_services/transition_to_collections",
      id: "transition_to_collections",
    },
    {
      name: "Custom",
      icon: Shield,
      url: "/patient_services/custom_patient_services",
      id: "custom_patient_services",
    },
  ],

  voice_ai: [
    {
      name: "Appointment Scheduling",
      icon: Shield,
      url: "/voice_ai/appointment_scheduling",
      id: "appointment_scheduling",
    },
    {
      name: "Insurance Verification",
      icon: Shield,
      url: "/voice_ai/insurance_verification",
      id: "insurance_verification",
    },
    {
      name: "Sales Support",
      icon: Shield,
      url: "/voice_ai/sales_support",
      id: "sales_support",
    },
    { name: "Custom", icon: Shield, url: null, id: null },
  ],

  revenue_cycle_administration: [
    {
      name: "Monthly/Quarterly/Annual Tasks",
      icon: Shield,
      url: "/revenue_cycle_administration/monthly_quarterly_annual_tasks",
      id: "monthly_quarterly_annual_tasks",
    },
    {
      name: "Reporting",
      icon: Shield,
      url: "/revenue_cycle_administration/reporting",
      id: "reporting",
    },
    {
      name: "KPI & Metrics",
      icon: Shield,
      url: "/revenue_cycle_administration/kpi_metrics",
      id: "kpi_metrics",
    },
    {
      name: "Compliance",
      icon: Shield,
      url: "/revenue_cycle_administration/compliance",
      id: "compliance",
    },
    {
      name: "Alerts & Notifications",
      icon: Shield,
      url: "/revenue_cycle_administration/alerts_notifications",
      id: "alerts_notifications",
    },
    {
      name: "Custom",
      icon: Shield,
      url: "/revenue_cycle_administration/custom_revenue_cycle_admin",
      id: "custom_revenue_cycle_admin",
    },
  ],
};

[
  {
    id: 8,
    module_name: "Payments",
    is_system: true,
    client: null,
    apps_count: 7,
  },
  {
    id: 10,
    module_name: "Voice AI",
    is_system: true,
    client: null,
    apps_count: 3,
  },
  {
    id: 3,
    module_name: "Patient Intake",
    is_system: true,
    client: null,
    apps_count: 5,
  },
  {
    id: 7,
    module_name: "Denials",
    is_system: true,
    client: null,
    apps_count: 4,
  },
  {
    id: 9,
    module_name: "Patient Services",
    is_system: true,
    client: null,
    apps_count: 5,
  },
  {
    id: 12,
    module_name: "Eligibility Verification",
    is_system: false,
    client: null,
    apps_count: 3,
  },
  {
    id: 11,
    module_name: "Revenue Cycle Administration",
    is_system: true,
    client: null,
    apps_count: 5,
  },
  {
    id: 4,
    module_name: "Scheduling & Registration",
    is_system: true,
    client: null,
    apps_count: 4,
  },
  {
    id: 6,
    module_name: "Claims",
    is_system: true,
    client: null,
    apps_count: 6,
  },
  {
    id: 5,
    module_name: "Charges & Entries",
    is_system: true,
    client: null,
    apps_count: 4,
  },
];
export const departmentIcons = [
  RiAddLine,
  RiAdminLine,
  RiAppsLine,
  RiBarChart2Fill,
  RiCalendarLine,
  RiChatVoiceAiLine,
  RiEyeLine,
  RiFile4Line,
  RiFileTextLine,
  RiFolderLine,
  RiHeartPulseLine,
  RiLogoutBoxLine,
  RiMessageLine,
  RiMic2AiFill,
  RiMoneyDollarCircleLine,
  RiServiceLine,
  RiSettings2Line,
  RiUserAddLine,
  RiVoiceRecognitionLine,
];
export const ehrIcons = [
  Grid2x2,
  CirclePlus,
  NotepadText,
  CircleDollarSign,
  CircleUser,
  IdCard,
  ChartNoAxesCombined,
  HeartPulse,
  Settings,
];
export const app_screen_data = {
  patient_intake: [
    {
      title: "Lorem Ipsum[Place Holder]",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do ut labore et dolore magna aliqua.[Place Holder]",
      icon: RiUserAddLine,
      iconBg: "bg-gradient-to-br from-blue-500 to-blue-600",
      id: "referral_agent",
      to: "/referral_agent",
      image: "",
    },
    {
      title: "Lorem Ipsum[Place Holder]",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do ut labore et dolore magna aliqua.[Place Holder]",
      icon: RiFileTextLine,
      iconBg: "bg-gradient-to-br from-green-500 to-green-600",
      id: "credential_agent",
      to: "/credential_agent",
      image: "",
    },
    {
      title: "Lorem Ipsum[Place Holder]",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do ut labore et dolore magna aliqua.[Place Holder]",
      icon: RiFileTextLine,
      iconBg: "bg-gradient-to-br from-teal-500 to-teal-600",
      id: "enrollment_agent",
      to: "/enrollment_agent",
      image: "",
    },
  ],
};

export const apps_data = [
  {
    header: "Insurance Verification",
    metrics: [
      "Total Verification Requests",
      "Verified Successfully",
      "Failed Verifications",
      "Pending Verifications",
      "Average Verification Time",
      "Top Insurance Providers Queried",
      "Verification Success Rate (%)",
      "Recent Verification Requests",
    ],
  },
  {
    header: "Claims Processing",
    metrics: [
      "Total Claims Processed",
      "Approved Claims",
      "Denied Claims",
      "Pending Claims",
      "Average Processing Time",
      "Claims Value Processed (Sum $)",
      "Approval Rate (%)",
      "Recent Claims Table",
    ],
  },
  {
    header: "Prior Authorization",
    metrics: [
      "Total Requests",
      "Approved Requests",
      "Denied Requests",
      "Pending Requests",
      "Average Approval Time",
      "Appeals Success Rate (%)",
      "Top Procedures by Volume",
      "Requests by Provider",
    ],
  },
  {
    header: "Claims Status",
    metrics: [
      "Total Claims Tracked",
      "Paid Claims",
      "Rejected Claims",
      "Pending Claims",
      "Average Resolution Time",
      "Top Payers by Claims Count",
      "Status Change Rate (%)",
      "Recent Status Updates",
    ],
  },
  {
    header: "Referral",
    metrics: [
      "Total Referrals",
      "Approved Referrals",
      "Denied Referrals",
      "Pending Referrals",
      "Average Processing Time",
      "Referral Success Rate (%)",
      "Referrals by Specialty",
      "Recent Referrals Table",
    ],
  },
  {
    header: "Intake",
    metrics: [
      "Total Patients Registered",
      "Completed Intakes",
      "Pending Intakes",
      "Dropped/Incomplete Intakes",
      "Average Intake Time",
      "Patient Demographics Breakdown",
      "Intake Completion Rate (%)",
      "Latest Patient Registrations",
    ],
  },
  {
    header: "Denials Management",
    metrics: [
      "Total Denials Received",
      "Denials Resolved",
      "Denials Pending",
      "Denials Reversed (Successfully Appealed)",
      "Average Resolution Time",
      "Top Denial Reasons",
      "Denials by Payer",
      "Recent Denials Table",
    ],
  },
  {
    header: "EOB to ERA",
    metrics: [
      "Total EOBs Processed",
      "Converted to ERA Successfully",
      "Failed Conversions",
      "Average Processing Time",
      "Value of Converted Claims ($)",
      "Top Payers in EOB Conversion",
      "Recent Conversions Table",
    ],
  },
  {
    header: "Credit Posting",
    metrics: [
      "Total Credits Posted",
      "Pending Credits",
      "Average Posting Time",
      "Total Credit Value ($)",
      "Credits by Payer",
      "Posting Accuracy Rate (%)",
      "Recent Credit Postings",
    ],
  },
  {
    header: "Payment Posting",
    metrics: [
      "Total Payments Posted",
      "Pending Payments",
      "Failed Postings",
      "Average Posting Time",
      "Total Payment Value ($)",
      "Payments by Method (ACH, Check, Card)",
      "Top Payers by Payment Value",
      "Recent Payment Postings",
    ],
  },
  {
    header: "Collections",
    metrics: [
      "Total Outstanding Amount ($)",
      "Collected Amount ($)",
      "Collection Rate (%)",
      "Pending Collections",
      "Average Collection Time",
      "Top Debtors by Amount",
      "Recent Collection Actions",
    ],
  },
  {
    header: "Payment Reminders",
    metrics: [
      "Total Reminders Sent",
      "Paid After Reminder",
      "Unpaid After Reminder",
      "Average Days to Payment",
      "Reminders by Payment Method",
      "Payment Success Rate After Reminder",
      "Recent Reminder Actions",
    ],
  },
  {
    header: "Invoice Processing",
    metrics: [
      "Total Invoices Processed",
      "Approved Invoices",
      "Rejected Invoices",
      "Pending Invoices",
      "Average Processing Time",
      "Total Invoice Value ($)",
      "Top Vendors by Invoice Count",
      "Recent Invoices Table",
    ],
  },
  {
    header: "Accounts Receivable",
    metrics: [
      "Total AR Amount ($)",
      "Overdue Amount ($)",
      "Current Amount ($)",
      "Average Days Outstanding (DSO)",
      "Collection Rate (%)",
      "AR Aging Report (0-30, 31-60, 61-90, 90+)",
      "Top Customers by Amount Owed",
    ],
  },
  {
    header: "Accounts Payable",
    metrics: [
      "Total AP Amount ($)",
      "Paid Amount ($)",
      "Pending Payments ($)",
      "Overdue Payments ($)",
      "Average Payment Time",
      "AP Aging Report",
      "Top Vendors by Amount Owed",
      "Recent Payment Transactions",
    ],
  },
  {
    header: "Compliance",
    metrics: [
      "Total Compliance Checks Performed",
      "Passed Checks",
      "Failed Checks",
      "Pending Reviews",
      "Common Compliance Failures",
      "Compliance Rate (%)",
      "Recent Compliance Reports",
    ],
  },
];
