const apps_columns = [
  {
    app_name: "Insurance Verification",
    app_id: 8,
    columns: [
      {
        name: "Organization",
        id: "organization",
        required: true,
        active: true,
      },
      { name: "Payer Name", id: "payer_name", required: true, active: true },
      {
        name: "Provider NPI",
        id: "provider_npi",
        required: true,
        active: true,
        condition: "one of NPI/Tax ID",
      },
      {
        name: "Provider Tax ID",
        id: "provider_tax_id",
        required: true,
        active: true,
        condition: "one of NPI/Tax ID",
      },
      {
        name: "Provider First Name",
        id: "provider_first_name",
        required: false,
        active: false,
      },
      {
        name: "Provider Last Name",
        id: "provider_last_name",
        required: false,
        active: false,
      },
      {
        name: "Provider Specialty / Taxonomy Code",
        id: "provider_specialty_taxonomy_code",
        required: false,
        active: false,
      },
      {
        name: "Place of Service",
        id: "place_of_service",
        required: false,
        active: false,
      },
      {
        name: "Billing Provider Details",
        id: "billing_provider_details",
        required: false,
        active: false,
      },
      {
        name: "Rendering Provider Details",
        id: "rendering_provider_details",
        required: false,
        active: false,
      },
      {
        name: "Member / Subscriber ID",
        id: "member_subscriber_id",
        required: true,
        active: true,
      },
      {
        name: "Patient First Name",
        id: "patient_first_name",
        required: true,
        active: true,
      },
      {
        name: "Patient Last Name",
        id: "patient_last_name",
        required: true,
        active: true,
      },
      { name: "Patient DOB", id: "patient_dob", required: true, active: true },
      {
        name: "Patient Middle Name",
        id: "patient_middle_name",
        required: false,
        active: false,
      },
      {
        name: "Patient Suffix",
        id: "patient_suffix",
        required: false,
        active: false,
      },
      {
        name: "Patient Gender",
        id: "patient_gender",
        required: false,
        active: false,
      },
      {
        name: "Subscriber Relationship",
        id: "subscriber_relationship",
        required: false,
        active: false,
      },
      {
        name: "Group Number",
        id: "group_number",
        required: false,
        active: false,
        condition: "if required",
      },
      {
        name: 'Service Date ("As of Date")',
        id: "service_date_as_of_date",
        required: true,
        active: true,
      },
      {
        name: "Benefit / Service Type",
        id: "benefit_service_type",
        required: true,
        active: true,
        condition: "or CPT/Place inputs",
      },
      {
        name: "Place of Service",
        id: "place_of_service_2",
        required: true,
        active: true,
        condition: "Required if no benefit type",
      },
      {
        name: "CPT/HCPCS Procedure Code(s)",
        id: "cpt_hcpcs_procedure_codes",
        required: true,
        active: true,
        condition: "Required if no benefit type",
      },
      {
        name: "Patient SSN",
        id: "patient_ssn",
        required: false,
        active: false,
      },
      {
        name: "Subscriber SSN",
        id: "subscriber_ssn",
        required: false,
        active: false,
      },
      {
        name: "Card Issue Date",
        id: "card_issue_date",
        required: false,
        active: false,
      },
      {
        name: "Payer Assigned Provider ID",
        id: "payer_assigned_provider_id",
        required: false,
        active: false,
      },
      {
        name: "Submitter ID",
        id: "submitter_id",
        required: false,
        active: false,
      },
      {
        name: "Patient State of Residence",
        id: "patient_state_of_residence",
        required: false,
        active: false,
      },
      {
        name: "Patient ZIP Code",
        id: "patient_zip_code",
        required: false,
        active: false,
      },
      {
        name: "Other Demographics",
        id: "other_demographics",
        required: false,
        active: false,
      },
    ],
  },
];

export default apps_columns;
