const default_iam_role = [
  {
    module_code: "ai_api_keys",
    module_name: "Ai Api Keys",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "roles_users",
    module_name: "Roles Users",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "billing_view",
    module_name: "Billing View",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "data_settings",
    module_name: "Data Settings",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "notifications",
    module_name: "Notifications",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "roi_estimated",
    module_name: "Roi Estimated",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "audit_logs_view",
    module_name: "Audit Logs View",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "column_settings",
    module_name: "Column Settings",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "create_edit_pods",
    module_name: "Create Edit Pods",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "payment_overview",
    module_name: "Payment Overview",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "agent_secret_keys",
    module_name: "Agent Secret Keys",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "start_stop_agents",
    module_name: "Start Stop Agents",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "create_edit_assets",
    module_name: "Create Edit Queues",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "developer_settings",
    module_name: "Developer Settings",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "module_permissions",
    module_name: "Module Permissions",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "roi_actual_savings",
    module_name: "Roi Actual Savings",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "edit_department",
    module_name: "Edit Department",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "create_edit_machines",
    module_name: "Create Edit Machines",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "create_edit_triggers",
    module_name: "Create Edit Triggers",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "monitoring_dashboard",
    module_name: "Monitoring Dashboard",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "agents_remove_edit",
    module_name: "Agents Remove Edit",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "licensing_subscription",
    module_name: "Licensing Subscription",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "analytics",
    module_name: "Analytics Patient Intake",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "audit_logs_export_delete",
    module_name: "Audit Logs Export Delete",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "view_performance_metrics",
    module_name: "View Performance Metrics",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "create_custom_dept_agents",
    module_name: "Create Custom Dept Agents",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "create_edit_projects_bots",
    module_name: "Create Edit Projects Bots",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "droidstudio_dashboard_view",
    module_name: "Droidstudio Dashboard View",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "requests_table_export",
    module_name: "Requests Table Export",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "roi_modify_calculation_settings",
    module_name: "Roi Modify Calculation Settings",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
  {
    module_code: "requests_table_edit_process_delete",
    module_name: "Requests Table Edit Process Delete",
    category: "unknown",
    permissions: {
      edit: true,
      view: true,
      create: true,
      delete: true,
      export: true,
    },
  },
];

export default default_iam_role;
