const serviceTypeOptions = [
  { value: "1", label: "Medical Care" },
  { value: "2", label: "Surgical" },
  { value: "3", label: "Consultation" },
  { value: "4", label: "Diagnostic X-Ray" },
  { value: "5", label: "Diagnostic Lab" },
  { value: "6", label: "Radiation Therapy" },
  { value: "7", label: "Anesthesia" },
  { value: "8", label: "Surgical Assistance" },
  { value: "9", label: "Other Medical" },
  { value: "10", label: "Blood Charges" },
  { value: "11", label: "Used Durable Medical Equipment" },
  { value: "12", label: "Durable Medical Equipment Purchase" },
  { value: "13", label: "Ambulatory Service Center Facility" },
  { value: "14", label: "Renal Supplies in the Home" },
  { value: "15", label: "Alternate Method Dialysis" },
  { value: "16", label: "Chronic Renal Disease (CRD) Equipment" },
  { value: "17", label: "Pre-Admission Testing" },
  { value: "18", label: "Durable Medical Equipment Rental" },
  { value: "19", label: "Pneumonia Vaccine" },
  { value: "20", label: "Second Surgical Opinion" },
  { value: "21", label: "Third Surgical Opinion" },
  { value: "22", label: "Social Work" },
  { value: "23", label: "Diagnostic Dental" },
  { value: "24", label: "Periodontics" },
  { value: "25", label: "Restorative" },
  { value: "26", label: "Endodontics" },
  { value: "27", label: "Maxillofacial Prosthetics" },
  { value: "28", label: "Adjunctive Dental Services" },
  { value: "30", label: "Health Benefit Plan Coverage" },
  { value: "32", label: "Plan Waiting Period" },
  { value: "33", label: "Chiropractic" },
  { value: "34", label: "Chiropractic Office Visits" },
  { value: "35", label: "Dental Care" },
  { value: "36", label: "Dental Crowns" },
  { value: "37", label: "Dental Accident" },
  { value: "38", label: "Orthodontics" },
  { value: "39", label: "Prosthodontics" },
  { value: "40", label: "Oral Surgery" },
  { value: "41", label: "Routine (Preventive) Dental" },
  { value: "42", label: "Home Health Care" },
  { value: "43", label: "Home Health Prescriptions" },
  { value: "44", label: "Home Health Visits" },
  { value: "45", label: "Hospice" },
  { value: "46", label: "Respite Care" },
  { value: "47", label: "Hospital" },
  { value: "48", label: "Hospital - Inpatient" },
  { value: "49", label: "Hospital - Room and Board" },
  { value: "50", label: "Hospital - Outpatient" },
  { value: "51", label: "Hospital - Emergency Accident" },
  { value: "52", label: "Hospital - Emergency Medical" },
  { value: "53", label: "Hospital - Ambulatory Surgical" },
  { value: "54", label: "Long Term Care" },
  { value: "55", label: "Major Medical" },
  { value: "56", label: "Medically Related Transportation" },
  { value: "57", label: "Air Transportation" },
  { value: "58", label: "Cabulance" },
  { value: "59", label: "Licensed Ambulance" },
  { value: "60", label: "General Benefits" },
  { value: "61", label: "In-vitro Fertilization" },
  { value: "62", label: "MRI/CAT Scan" },
  { value: "63", label: "Donor Procedures" },
  { value: "64", label: "Acupuncture" },
  { value: "65", label: "Newborn Care" },
  { value: "66", label: "Pathology" },
  { value: "67", label: "Smoking Cessation" },
  { value: "68", label: "Well Baby Care" },
  { value: "69", label: "Maternity" },
  { value: "70", label: "Transplants" },
  { value: "71", label: "Audiology Exam" },
  { value: "72", label: "Inhalation Therapy" },
  { value: "73", label: "Diagnostic Medical" },
  { value: "74", label: "Private Duty Nursing" },
  { value: "75", label: "Prosthetic Device" },
  { value: "76", label: "Dialysis" },
  { value: "77", label: "Otological Exam" },
  { value: "78", label: "Chemotherapy" },
  { value: "79", label: "Allergy Testing" },
  { value: "80", label: "Immunizations" },
  { value: "81", label: "Routine Physical" },
  { value: "82", label: "Family Planning" },
  { value: "83", label: "Infertility" },
  { value: "84", label: "Abortion" },
  { value: "85", label: "AIDS" },
  { value: "86", label: "Emergency Services" },
  { value: "87", label: "Cancer" },
  { value: "88", label: "Pharmacy" },
  { value: "89", label: "Free Standing Prescription Drug" },
  { value: "90", label: "Mail Order Prescription Drug" },
  { value: "91", label: "Brand Name Prescription Drug" },
  { value: "92", label: "Generic Prescription Drug" },
  { value: "93", label: "Podiatry" },
  { value: "94", label: "Podiatry - Office Visits" },
  { value: "95", label: "Podiatry - Nursing Home Visits" },
  { value: "96", label: "Professional (Physician)" },
  { value: "97", label: "Anesthesiologist" },
  { value: "98", label: "Professional (Physician) Visit - Office" },
  { value: "99", label: "Professional (Physician) Visit - Inpatient" },
  { value: "A0", label: "Professional (Physician) Visit - Outpatient" },
  { value: "A1", label: "Professional (Physician) Visit - Nursing Home" },
  {
    value: "A2",
    label: "Professional (Physician) Visit - Skilled Nursing Facility",
  },
  { value: "A3", label: "Professional (Physician) Visit - Home" },
  { value: "A4", label: "Psychiatric" },
  { value: "A5", label: "Psychiatric - Room and Board" },
  { value: "A6", label: "Psychotherapy" },
  { value: "A7", label: "Psychiatric - Inpatient" },
  { value: "A8", label: "Psychiatric - Outpatient" },
  { value: "A9", label: "Rehabilitation" },
  { value: "AA", label: "Rehabilitation - Room and Board" },
  { value: "AB", label: "Rehabilitation - Inpatient" },
  { value: "AC", label: "Rehabilitation - Outpatient" },
  { value: "AD", label: "Occupational Therapy" },
  { value: "AE", label: "Physical Medicine" },
  { value: "AF", label: "Speech Therapy" },
  { value: "AG", label: "Skilled Nursing Care" },
  { value: "AH", label: "Skilled Nursing Care - Room and Board" },
  { value: "AI", label: "Substance Abuse" },
  { value: "AJ", label: "Alcoholism" },
  { value: "AK", label: "Drug Addiction" },
  { value: "AL", label: "Vision (Optometry)" },
  { value: "AM", label: "Frames" },
  { value: "AN", label: "Routine Vision Exam" },
  { value: "AO", label: "Lenses" },
  { value: "AQ", label: "Nonmedically Necessary Physical" },
  { value: "AR", label: "Experimental Drug Therapy" },
  { value: "B1", label: "Burn Care" },
  { value: "BA", label: "Independent Medical Evaluation" },
  { value: "BB", label: "Partial Hospitalization (Psychiatric)" },
  { value: "BC", label: "Day Care (Psychiatric)" },
  { value: "BD", label: "Cognitive Therapy" },
  { value: "BE", label: "Massage Therapy" },
  { value: "BF", label: "Pulmonary Rehabilitation" },
  { value: "BG", label: "Cardiac Rehabilitation" },
  { value: "BH", label: "Pediatric" },
  { value: "BI", label: "Nursery" },
  { value: "BJ", label: "Skin" },
  { value: "BK", label: "Orthopedic" },
  { value: "BL", label: "Cardiac" },
  { value: "BM", label: "Lymphatic" },
  { value: "BN", label: "Gastrointestinal" },
  { value: "BP", label: "Endocrine" },
  { value: "BQ", label: "Neurology" },
  { value: "BR", label: "Eye" },
  { value: "BS", label: "Invasive Procedures" },
  { value: "BT", label: "Gynecological" },
  { value: "BU", label: "Obstetrical" },
  { value: "BV", label: "Obstetrical/Gynecological" },
  { value: "BW", label: "Mail Order Prescription Drug - Brand Name" },
  { value: "BX", label: "Mail Order Prescription Drug - Generic" },
  { value: "BY", label: "Physician Visit - Office: Sick" },
  { value: "BZ", label: "Physician Visit - Office: Well" },
  { value: "C1", label: "Coronary Care" },
  { value: "CA", label: "Private Duty Nursing - Inpatient" },
  { value: "CB", label: "Private Duty Nursing - Home" },
  { value: "CC", label: "Surgical Benefits - Professional (Physician)" },
  { value: "CD", label: "Surgical Benefits - Facility" },
  { value: "CE", label: "Mental Health Provider - Inpatient" },
  { value: "CF", label: "Mental Health Provider - Outpatient" },
  { value: "CG", label: "Mental Health Facility - Inpatient" },
  { value: "CH", label: "Mental Health Facility - Outpatient" },
  { value: "CI", label: "Substance Abuse Facility - Inpatient" },
  { value: "CJ", label: "Substance Abuse Facility - Outpatient" },
  { value: "CM", label: "Mammogram, High Risk Patient" },
  { value: "CN", label: "Mammogram, Low Risk Patient" },
  { value: "CO", label: "Flu Vaccination" },
  { value: "CP", label: "Eyewear and Eyewear Accessories" },
  { value: "CQ", label: "Case Management" },
  { value: "DG", label: "Dermatology" },
  { value: "DM", label: "Durable Medical Equipment" },
  { value: "DS", label: "Diabetic Supplies" },
  { value: "GF", label: "Generic Prescription Drug - Formulary" },
  { value: "GN", label: "Generic Prescription Drug - Non-Formulary" },
  { value: "GY", label: "Allergy" },
  { value: "IC", label: "Intensive Care" },
  { value: "MH", label: "Mental Health" },
  { value: "NI", label: "Neonatal Intensive Care" },
  { value: "ON", label: "Oncology" },
  { value: "PT", label: "Physical Therapy" },
  { value: "PU", label: "Pulmonary" },
  { value: "RN", label: "Renal" },
  { value: "RT", label: "Residential Psychiatric Treatment" },
  { value: "TC", label: "Transitional Care" },
  { value: "TN", label: "Transitional Nursery Care" },
  { value: "UC", label: "Urgent Care" },
];

export default serviceTypeOptions;
