# Generated by Django 5.2.4 on 2026-01-19 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelehealthAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_id', models.CharField(max_length=255)),
                ('external_user_id', models.CharField(max_length=255)),
                ('attendee_name', models.CharField(max_length=255)),
                ('join_token', models.TextField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_video_enabled', models.BooleanField(default=True)),
                ('is_screen_sharing', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'telehealth_attendee',
            },
        ),
        migrations.CreateModel(
            name='TelehealthMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('external_meeting_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('media_region', models.CharField(blank=True, max_length=50, null=True)),
                ('media_placement', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_recording', models.BooleanField(default=False)),
                ('recording_started_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_start_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('meeting_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_description', models.TextField(blank=True, null=True)),
                ('creation_email_sent', models.BooleanField(default=False)),
                ('reminder_email_sent', models.BooleanField(default=False)),
                ('start_email_sent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('started', 'Started'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('appoinment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appoinments', to='tenant_app.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telehealth_meeting',
            },
        ),
        migrations.CreateModel(
            name='TelehealthChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('system', 'System'), ('file', 'File')], default='text', max_length=10)),
                ('content', models.TextField()),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tenant_telehealth.telehealthattendee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='tenant_telehealth.telehealthmeeting')),
            ],
            options={
                'db_table': 'telehealth_chatmessage',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TelehealthAudioCallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initiating', 'Initiating'), ('ringing', 'Ringing'), ('connected', 'Connected'), ('on_hold', 'On Hold'), ('ended', 'Ended'), ('failed', 'Failed')], default='initiating', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('audio_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_sessions', to='tenant_telehealth.telehealthattendee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_sessions', to='tenant_telehealth.telehealthmeeting')),
            ],
            options={
                'db_table': 'telehealth_audiocall_session',
            },
        ),
        migrations.AddField(
            model_name='telehealthattendee',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='tenant_telehealth.telehealthmeeting'),
        ),
        migrations.CreateModel(
            name='TelehealthMeetingRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('recording', 'Recording'), ('paused', 'Paused'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='starting', max_length=20)),
                ('recording_type', models.CharField(choices=[('audio', 'Audio Only'), ('video', 'Video'), ('screen', 'Screen Share'), ('composite', 'Composite')], default='composite', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_size_mb', models.FloatField(blank=True, null=True)),
                ('s3_bucket', models.CharField(blank=True, max_length=255, null=True)),
                ('s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='tenant_telehealth.telehealthmeeting')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_recordings', to='tenant_telehealth.telehealthattendee')),
            ],
            options={
                'db_table': 'telehealth_meetingrecords',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TelehealthScreenShareSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='starting', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(default='screen', max_length=50)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_shares', to='tenant_telehealth.telehealthattendee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_shares', to='tenant_telehealth.telehealthmeeting')),
            ],
            options={
                'db_table': 'telehealth_screenshare_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='telehealthattendee',
            unique_together={('meeting', 'external_user_id')},
        ),
        migrations.CreateModel(
            name='ScheduledMeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('is_organizer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_attendees', to='tenant_telehealth.telehealthmeeting')),
            ],
            options={
                'db_table': 'scheduled_meeting_attendee',
                'unique_together': {('meeting', 'email')},
            },
        ),
    ]
