# Generated by Django 5.2.4 on 2026-01-19 12:38

import django.db.models.deletion
import tenant_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('patient_appointment', 'Patient Appointment'), ('other_appointment', 'Other Appointment')], max_length=30)),
                ('confirmationstatus', models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('scheduled', 'Scheduled'), ('reminder_sent', 'Reminder Sent'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('arrived', 'Arrived'), ('checked_in', 'Checked In'), ('in_progress', 'In Progress'), ('roomed', 'Roomed'), ('in_session', 'In Session'), ('checked_out', 'Checked Out'), ('completed', 'Completed'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('self_pay', models.BooleanField(default=False)),
                ('copay_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposite_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('self_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'patient_appoitnment',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mrn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Medical Record Number')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('ssn', models.CharField(blank=True, max_length=11, null=True, verbose_name='Social Security Number')),
                ('gender', models.CharField(choices=[('Unknown', 'Unknown'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Unknown', max_length=20)),
                ('pronouns', models.CharField(blank=True, choices=[('He/Him', 'He/Him'), ('She/Her', 'She/Her'), ('They/Them', 'They/Them')], max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, null=True)),
                ('referral_source', models.CharField(choices=[('Not Specified', 'Not Specified'), ('Provider', 'Provider'), ('Friend', 'Friend'), ('Advertisement', 'Advertisement')], default='Not Specified', max_length=50)),
                ('default_service_location', models.CharField(choices=[('Not Specified', 'Not Specified'), ('Main Office', 'Main Office'), ('Satellite Clinic', 'Satellite Clinic')], default='Not Specified', max_length=50)),
                ('employment_status', models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Retired', 'Retired'), ('Student', 'Student')], max_length=20, null=True)),
                ('employer', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('home_phone_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('work_phone_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_phone_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('enable_auto_reminders', models.BooleanField(default=False)),
                ('send_email_notifications', models.BooleanField(default=True)),
                ('emergency_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_phone_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('responsible_party_different', models.BooleanField(default=False)),
                ('default_payer_scenario', models.CharField(blank=True, choices=[('ATTORNEY_LIEN', 'Attorney Lien'), ('AUTO', 'Auto Insurance'), ('BCBS', 'BC/BS'), ('BCBS_HMO', 'BC/BS HMO'), ('COMMERCIAL', 'Commercial'), ('HMO', 'HMO'), ('MEDICAID', 'Medicaid'), ('MEDICAID_HMO', 'Medicaid HMO'), ('MEDICARE', 'Medicare'), ('PPO', 'PPO'), ('SELF_PAY', 'Self Pay'), ('TRICARE', 'Tricare'), ('VA', 'VA'), ('WORKERS_COMP', 'Workers Comp'), ('WC_APPLICANT', 'Workers Comp - Applicant'), ('WC_DEFENSE', 'Workers Comp - Defense')], max_length=50, null=True)),
                ('insurance_name', models.JSONField(blank=True, null=True, validators=[tenant_app.models.validate_insurance_name])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('memberId', models.CharField(blank=True, max_length=50, null=True)),
                ('serviceTypeCode', models.CharField(blank=True, max_length=50, null=True)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='pms/patient_profiles/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligibility_status', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_network', models.CharField(blank=True, max_length=50, null=True)),
                ('eligibility_last_checked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient_details',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, null=True)),
                ('file_path', models.TextField(blank=True, help_text='Absolute or relative path if stored externally', null=True)),
                ('label', models.CharField(choices=[('Photo Id', 'Photo Id'), ('Insurance Card', 'Insurance Card'), ('Medical Records', 'Medical Records'), ('Miscellaneous', 'Miscellaneous')], default='active', max_length=40, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Old', 'Old'), ('New', 'New')], default='active', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tenant_app.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenant_app.patient')),
            ],
            options={
                'db_table': 'patient_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='tenant_app.patient'),
        ),
        migrations.CreateModel(
            name='PatientProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField()),
                ('NPI', models.CharField(max_length=100)),
                ('practice_name', models.CharField(max_length=100)),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_type', models.CharField(blank=True, max_length=100, null=True)),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('medicare_ptan', models.CharField(blank=True, max_length=100, null=True)),
                ('medicaid_id', models.CharField(blank=True, max_length=100, null=True)),
                ('taxid_ein', models.CharField(blank=True, max_length=100, null=True)),
                ('taxid_ssn', models.CharField(blank=True, max_length=100, null=True)),
                ('telehealth', models.CharField(blank=True, max_length=50, null=True)),
                ('taxonomy', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('week', models.JSONField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('service', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_license_number', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patient_provider',
                'constraints': [models.UniqueConstraint(condition=models.Q(('taxid_ein__isnull', False)), fields=('taxid_ein',), name='unique_taxid_ein'), models.UniqueConstraint(condition=models.Q(('taxid_ssn__isnull', False)), fields=('taxid_ssn',), name='unique_taxid_ssn')],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='default_rendering_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_rendering_provider', to='tenant_app.patientprovider'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pcp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_Care_physician', to='tenant_app.patientprovider'),
        ),
        migrations.AddField(
            model_name='patient',
            name='referring_physician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referring_physician', to='tenant_app.patientprovider'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='tenant_app.patientprovider'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_non_null_email'),
        ),
    ]
