# Generated by Django 5.1.15 on 2026-01-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('patient_appointment', 'Patient Appointment'), ('other_appointment', 'Other Appointment'), ('telehealth_appointment', 'Telehealth Appointment')], max_length=30),
        ),
    ]
