# Generated by Django 5.1.6 on 2026-02-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0002_alter_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='responsible_party_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_party_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_party_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_party_relation',
            field=models.CharField(blank=True, choices=[('Parent', 'Parent'), ('Spouse', 'Spouse'), ('Guardian', 'Guardian'), ('Other', 'Other'), ('Child', 'Child'), ('Sibling', 'Sibling')], max_length=50, null=True),
        ),
    ]
