# Generated by Django 5.2.4 on 2025-08-26 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255, unique=True)),
                ('version', models.CharField(default='0.0.1', max_length=20)),
            ],
            options={
                'db_table': 'appversion',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('project', models.CharField(choices=[('ABA', 'ABA'), ('Transcribe', 'Transcribe'), ('Insurance Verification', 'Insurance Verification'), ('Claims Processing', 'Claims Processing'), ('Prior Authorization', 'Prior Authorization'), ('Claims Status', 'Claims Status')], max_length=50)),
                ('dev_count', models.PositiveIntegerField(default=0)),
                ('prod_count', models.PositiveIntegerField(default=0)),
                ('license_key', models.CharField(max_length=50, unique=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('machine_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('mail', models.CharField(blank=True, max_length=255, null=True)),
                ('roles', models.CharField(choices=[('default_user', 'Default User'), ('client', 'Client'), ('user', 'User'), ('admin', 'Admin')], default='default_user', max_length=20)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.client')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
