# Generated by Django 5.2.4 on 2025-08-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='project',
        ),
        migrations.AddField(
            model_name='client',
            name='license_tier',
            field=models.CharField(choices=[('standard', 'STANDARD'), ('pro', 'PRO'), ('enterprise', 'ENTERPRISE')], default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='license_key',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
