# Generated by Django 5.2.4 on 2025-08-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_client_project_client_license_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
