# Generated by Django 5.2.4 on 2025-09-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_client_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='additional_cost',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
