# Generated by Django 5.2.4 on 2025-09-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_client_additional_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='additional_cost',
        ),
    ]
