# Generated by Django 5.2.4 on 2025-09-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_client_additional_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='additional_cost',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
