# Generated by Django 5.2.4 on 2025-09-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_client_additional_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='license_tier',
            field=models.CharField(choices=[('standard', 'STANDARD'), ('pro', 'PRO'), ('enterprise', 'ENTERPRISE'), ('lite', 'LITE')], default='standard', max_length=50),
        ),
    ]
