# Generated by Django 5.2.4 on 2025-09-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_client_license_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tier_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
