# Generated by Django 5.2.4 on 2025-09-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_client_tier_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_user',
            field=models.BooleanField(default=False),
        ),
    ]
