# Generated by Django 5.2.4 on 2025-09-16 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_verify_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verify_user',
        ),
    ]
