# Generated by Django 5.2.4 on 2025-09-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_verify_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_verify',
            field=models.BooleanField(default=False),
        ),
    ]
