# Generated by Django 5.2.4 on 2025-09-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_user_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='license_tier',
            field=models.CharField(choices=[('standard', 'STANDARD'), ('pro', 'PRO'), ('enterprise', 'ENTERPRISE'), ('lite', 'LITE'), ('free trail', 'FREE TRAIL')], default='free trail', max_length=50),
        ),
    ]
