# Generated by Django 5.2.4 on 2025-09-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
