# Generated by Django 5.2.4 on 2025-10-24 11:45

import django.db.models.deletion
import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_client_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('monitoring', 'Monitoring'), ('agent_management', 'Agent Management'), ('analytics', 'Analytics'), ('droid_studio', 'DroidStudio'), ('roi', 'ROI'), ('settings', 'Settings'), ('billing', 'Billing')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='mfa_qr/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('default_user', 'Default User'), ('client', 'Client'), ('user', 'User'), ('admin', 'Admin'), ('owner', 'Owner'), ('developer', 'Developer'), ('project_manager', 'Project Manager'), ('analyst', 'Analyst'), ('bot_operator', 'Bot Operator'), ('viewer', 'Viewer')], default='default_user', max_length=20),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(default=dict, help_text='JSON object mapping module codes to permission flags')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles serve as templates for client roles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='If NULL, this is a system-wide template role', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.client')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['is_system_role', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['client', 'code'], name='roles_client__257c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_system_role'], name='roles_is_syst_135658_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('code', 'client')},
        ),
    ]
