# Generated by Django 5.2.4 on 2025-11-04 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_module_user_is_superuser_user_mfa_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.JSONField(default=list, help_text='List of recipient emails')),
                ('schedule', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_alert', to='accounts.client')),
            ],
            options={
                'db_table': 'invoice_alerts',
                'ordering': ['schedule'],
            },
        ),
        migrations.CreateModel(
            name='SummaryReportAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.JSONField(default=list, help_text='List of recipient emails')),
                ('schedule', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=50)),
                ('report_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_report_alert', to='accounts.client')),
            ],
            options={
                'db_table': 'summary_report_alerts',
                'ordering': ['report_type', 'schedule'],
            },
        ),
    ]
