# Generated by Django 5.2.4 on 2025-11-04 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_invoicealert_summaryreportalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='client',
            name='vm_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
