# Generated by Django 5.2.4 on 2025-11-10 16:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_client_effective_date_client_vm_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_count', models.PositiveIntegerField(blank=True, null=True)),
                ('dev_count', models.PositiveIntegerField(blank=True, null=True)),
                ('prod_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('license_tier', models.CharField(blank=True, max_length=50, null=True)),
                ('tier_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('effective_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='accounts.client')),
            ],
            options={
                'db_table': 'client_change_log',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['client', 'effective_from'], name='client_chan_client__14b635_idx'), models.Index(fields=['client', 'effective_to'], name='client_chan_client__47babb_idx'), models.Index(fields=['license_tier'], name='client_chan_license_353c3f_idx'), models.Index(condition=models.Q(('effective_to__isnull', True)), fields=['client'], name='active_logs_idx')],
            },
        ),
    ]
