# Generated by Django 5.2.4 on 2025-11-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_clientchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientchangelog',
            name='additional_cost',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
