# Generated by Django 5.2.4 on 2025-11-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_clientchangelog_additional_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_vm_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientchangelog',
            name='client_vm_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
