# Generated by Django 5.2.4 on 2025-11-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_client_client_vm_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryreportalert',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicealert',
            name='schedule',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=50, null=True),
        ),
    ]
