# Generated by Django 5.2.4 on 2025-11-25 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_summaryreportalert_schedule_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryreportalert',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_report_alerts', to='accounts.client'),
        ),
    ]
