# Generated by Django 5.2.4 on 2025-12-02 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_summaryreportalert_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_virtual_machine_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_vm_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='cost_of_vm',
            field=models.CharField(blank=True, choices=[('actual', 'Actual Cost'), ('sop', 'SOP Cost')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='dev_vm_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='prod_vm_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clientchangelog',
            name='client_virtual_machine_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clientchangelog',
            name='client_vm_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clientchangelog',
            name='cost_of_vm',
            field=models.CharField(blank=True, choices=[('actual', 'Actual Cost'), ('sop', 'SOP Cost')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientchangelog',
            name='dev_vm_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clientchangelog',
            name='prod_vm_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
