# Generated by Django 5.2.4 on 2025-12-03 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_client_client_virtual_machine_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicealert',
            name='schedule',
            field=models.CharField(blank=True, choices=[('end-of-month', 'End of the Month')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='summaryreportalert',
            name='schedule',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('start-of-month', 'Start of the Month'), ('end-of-month', 'End of the Month')], max_length=50),
        ),
    ]
