# Generated by Django 5.2.4 on 2025-12-03 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_invoicealert_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicealert',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_alerts', to='accounts.client'),
        ),
    ]
