# Generated by Django 5.1.15 on 2025-12-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_invoicealert_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_emr_module',
            field=models.BooleanField(default=False, help_text='Enable isolated EMR/PHR schema'),
        ),
        migrations.AddField(
            model_name='client',
            name='schema_name',
            field=models.CharField(blank=True, default='public', help_text="Auto-set to 'public' for non-EMR, unique tenant_xxx for EMR", max_length=63, null=True),
        ),
    ]
