# Generated by Django 5.2.4 on 2026-01-04 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_client_has_emr_module_client_schema_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleHealthGuestAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('meeting_db_id', models.IntegerField(help_text='TelehealthMeeting database ID')),
                ('user_type', models.CharField(choices=[('patient', 'Patient'), ('provider', 'Provider'), ('guest', 'Guest')], default='patient', max_length=20)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('linked_patient_id', models.IntegerField(blank=True, help_text='Patient ID in tenant schema', null=True)),
                ('tenant_schema', models.CharField(max_length=63)),
                ('is_active', models.BooleanField(default=True)),
                ('is_used', models.BooleanField(default=False)),
                ('can_share_screen', models.BooleanField(default=True)),
                ('can_record', models.BooleanField(default=False)),
                ('can_chat', models.BooleanField(default=True)),
                ('can_use_video', models.BooleanField(default=True)),
                ('can_use_audio', models.BooleanField(default=True)),
                ('can_mute_others', models.BooleanField(default=False)),
                ('can_remove_participants', models.BooleanField(default=False)),
                ('can_end_meeting', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('max_access_count', models.IntegerField(default=10)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_addresses', models.JSONField(blank=True, default=list)),
                ('user_agents', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_guest_tokens', to=settings.AUTH_USER_MODEL)),
                ('linked_user', models.ForeignKey(blank=True, help_text="Link to provider's user account if applicable", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telehealth_guest_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telehealth_guest_token',
                'indexes': [models.Index(fields=['token_hash'], name='telehealth__token_h_c18af2_idx'), models.Index(fields=['tenant_schema', 'is_active'], name='telehealth__tenant__037cb9_idx'), models.Index(fields=['meeting_db_id', 'user_type'], name='telehealth__meeting_6962e4_idx'), models.Index(fields=['expires_at'], name='telehealth__expires_c73274_idx')],
            },
        ),
    ]
