# Generated by Django 5.2.4 on 2026-01-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_telehealthguestaccesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telehealthguestaccesstoken',
            name='max_access_count',
            field=models.IntegerField(default=100000),
        ),
    ]
