# Generated by Django 5.2.4 on 2026-02-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_telehealthguestaccesstoken_max_access_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='number_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
