# Generated by Django 5.2.4 on 2026-03-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_client_number_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='voice_ai_license',
            field=models.BooleanField(default=False, help_text='Enable Voice AI License'),
        ),
    ]
