# Generated by Django 5.1.6 on 2026-06-30 21:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_client_voice_ai_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='allowed_ips',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), blank=True, default=list, help_text="List of allowed IP addresses (e.g. ['192.168.1.1', '10.0.0.1'])", size=None),
        ),
    ]
