# Generated by Django 5.2.4 on 2025-09-02 12:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_sub_app_agent_api_secretkeys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agent_API_SecretKeys',
            new_name='Agent_API_SecretKeyss',
        ),
        migrations.RenameModel(
            old_name='Sub_app',
            new_name='Sub_apps',
        ),
        migrations.AlterModelTable(
            name='agent_api_secretkeyss',
            table='sub_agent_apikeys',
        ),
        migrations.AlterModelTable(
            name='sub_apps',
            table='sub_agents',
        ),
    ]
