# Generated by Django 5.2.4 on 2025-09-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_rename_agent_api_secretkeys_agent_api_secretkeyss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='max_retries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
