# Generated by Django 5.2.4 on 2025-09-03 07:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_app_max_retries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agent_api_secretkeyss',
            unique_together={('user', 'sub_app')},
        ),
        migrations.AlterUniqueTogether(
            name='generatedapi',
            unique_together={('user', 'apps')},
        ),
    ]
