# Generated by Django 5.2.4 on 2025-09-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_agent_api_secretkeyss_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='max_retries',
        ),
        migrations.AddField(
            model_name='generatedapi',
            name='max_retries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
