# Generated by Django 5.2.4 on 2025-09-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_remove_app_max_retries_generatedapi_max_retries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedapi',
            name='max_retries',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
