# Generated by Django 5.2.4 on 2025-09-09 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_customcolumn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appscolumnsetting',
            name='app_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.app'),
        ),
    ]
