# Generated by Django 5.2.4 on 2025-09-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_alter_appscolumnsetting_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_api_secretkeyss',
            name='task_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=20),
        ),
    ]
