# Generated by Django 5.2.4 on 2025-09-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_agent_api_secretkeyss_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_api_secretkeyss',
            name='task_status',
        ),
        migrations.AddField(
            model_name='generatedapi',
            name='task_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=20),
        ),
    ]
