# Generated by Django 5.2.4 on 2025-10-16 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_modulepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('agent', 'Agent'), ('api_key', 'API Key'), ('login', 'Login'), ('logout', 'Logout'), ('modules', 'Modules')], max_length=100)),
                ('log_status', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
