# Generated by Django 5.2.4 on 2025-10-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_module_user_is_superuser_user_mfa_enabled_and_more'),
        ('modules', '0014_logrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='hide_app',
            field=models.ManyToManyField(blank=True, related_name='hide_apps', to='accounts.client'),
        ),
    ]
