# Generated by Django 5.2.4 on 2025-08-26 07:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenses', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerDetails',
            fields=[
                ('trigger_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cron_query', models.TextField(blank=True, null=True)),
                ('cron_command', models.TextField(blank=True, null=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('is_created', models.BooleanField(default=False)),
                ('cron_flag', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scaling', models.CharField(default='100', max_length=10)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggers', to='licenses.license')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='projects.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trigger',
                'verbose_name_plural': 'Triggers',
                'db_table': 'triggers',
                'managed': True,
                'indexes': [models.Index(fields=['project', 'task', 'created_at'], name='triggers_project_b8874b_idx')],
            },
        ),
    ]
