# Generated by Django 5.2.4 on 2025-09-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerdetails',
            name='agentid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
