# Generated by Django 5.2.4 on 2025-09-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0002_triggerdetails_agentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerdetails',
            name='code_env',
            field=models.CharField(default='tasks-json', max_length=20),
        ),
    ]
