# Generated by Django 5.2.4 on 2025-09-30 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0003_triggerdetails_code_env'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('started', 'Started'), ('success', 'Success'), ('failure', 'Failure')], default=None, max_length=20, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('exception', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='trigger.triggerdetails')),
            ],
            options={
                'db_table': 'trigger_status',
                'ordering': ['-created_at'],
            },
        ),
    ]
