# Generated by Django 5.1.4 on 2026-07-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='graph',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='automation',
            name='action_skill',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='automation',
            name='trigger_skill',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
