# Generated by Django 5.1.4 on 2026-07-21 05:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_memberships_alter_user_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(blank=True, max_length=120)),
                ('payer_id', models.CharField(blank=True, max_length=40)),
                ('member_id', models.CharField(blank=True, max_length=60)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('dob', models.CharField(blank=True, max_length=20)),
                ('npi', models.CharField(blank=True, max_length=20)),
                ('cpt', models.CharField(blank=True, max_length=40)),
                ('service_types', models.JSONField(blank=True, default=list)),
                ('coverage_status', models.CharField(blank=True, max_length=20)),
                ('plan_type', models.CharField(blank=True, max_length=20)),
                ('plan_name', models.CharField(blank=True, max_length=140)),
                ('group_number', models.CharField(blank=True, max_length=60)),
                ('subscriber', models.CharField(blank=True, max_length=20)),
                ('effective_date', models.CharField(blank=True, max_length=20)),
                ('termination_date', models.CharField(blank=True, max_length=20)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('normalized', models.JSONField(blank=True, default=dict)),
                ('vob_summary', models.TextField(blank=True)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('ai_model', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(default='completed', max_length=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_checks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checks', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
