# Generated by Django 5.1.4 on 2026-07-19 02:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_avatar_user_mfa_enabled_user_mfa_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('persona', models.CharField(blank=True, help_text='A short personality descriptor.', max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused')], default='DRAFT', max_length=10)),
                ('voice', models.CharField(choices=[('ARIA', 'Aria — warm, friendly'), ('JAMES', 'James — calm, professional'), ('SOFIA', 'Sofia — bright, energetic'), ('LEO', 'Leo — deep, reassuring'), ('NOVA', 'Nova — neutral, clear')], default='ARIA', max_length=20)),
                ('language', models.CharField(choices=[('en-US', 'English (US)'), ('en-GB', 'English (UK)'), ('es-ES', 'Spanish'), ('fr-FR', 'French'), ('de-DE', 'German'), ('hi-IN', 'Hindi')], default='en-US', max_length=10)),
                ('greeting', models.TextField(blank=True, help_text='The first thing the agent says.')),
                ('system_prompt', models.TextField(blank=True, help_text='Instructions that define how the agent behaves.')),
                ('model', models.CharField(choices=[('claude-haiku-4-5', 'Haiku 4.5 — fastest'), ('claude-sonnet-5', 'Sonnet 5 — balanced'), ('claude-opus-4-8', 'Opus 4.8 — most capable')], default='claude-sonnet-5', max_length=40)),
                ('temperature', models.FloatField(default=0.7, help_text='0 = focused/deterministic, 1 = creative.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agents', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_agents', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
