# Generated by Django 5.1.4 on 2026-07-20 22:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceai', '0003_agentinstruction_ivrconfig_vobcall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceagent',
            name='agent_type',
            field=models.CharField(default='Conversation', max_length=40),
        ),
        migrations.AddField(
            model_name='voiceagent',
            name='background_audio',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='voiceagent',
            name='call_direction',
            field=models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('REMINDER', 'Remainder'), ('OUTBOUND_PATIENT', 'Outbound Patient')], default='INBOUND', max_length=20),
        ),
        migrations.AddField(
            model_name='voiceagent',
            name='call_recording',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='voiceagent',
            name='continue_recording_after_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voiceagent',
            name='delay_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voiceagent',
            name='end_call_messages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='voiceagent',
            name='forward_messages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='voiceagent',
            name='keys',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='voiceagent',
            name='max_concurrent_calls',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='voiceagent',
            name='phone_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='voiceagent',
            name='retry',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voiceagent',
            name='system_integration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voiceagent',
            name='voice_gender',
            field=models.CharField(default='Female', max_length=10),
        ),
        migrations.AddField(
            model_name='voiceagent',
            name='voice_type',
            field=models.CharField(choices=[('REALTIME', 'Real Time'), ('STT_TTS', 'STT-TTS')], default='STT_TTS', max_length=12),
        ),
        migrations.CreateModel(
            name='AgentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('voice_type', models.CharField(default='STT-TTS', max_length=20)),
                ('agent_type', models.CharField(default='Conversation', max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='voiceai.voiceagent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
