# Generated by Django 5.1.4 on 2026-07-21 04:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_memberships_alter_user_tenant'),
        ('voiceai', '0004_voiceagent_agent_type_voiceagent_background_audio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=150)),
                ('member_id', models.CharField(blank=True, max_length=60)),
                ('npi', models.CharField(blank=True, max_length=20)),
                ('group_number', models.CharField(blank=True, max_length=60)),
                ('dob', models.CharField(blank=True, max_length=20)),
                ('payer', models.CharField(blank=True, max_length=120)),
                ('insurance_phone', models.CharField(blank=True, max_length=40)),
                ('cpt_codes', models.CharField(blank=True, max_length=120)),
                ('voice', models.CharField(default='rachel', max_length=20)),
                ('dtmf_mode', models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual')], default='AUTO', max_length=8)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('DIALING', 'Dialing'), ('IVR', 'Navigating IVR'), ('CONNECTED', 'Live with rep'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=10)),
                ('mode', models.CharField(default='ivr', max_length=10)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('eligibility_data', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('decision', models.CharField(blank=True, max_length=40)),
                ('recording_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_calls', to=settings.AUTH_USER_MODEL)),
                ('instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_calls', to='voiceai.agentinstruction')),
                ('ivr_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_calls', to='voiceai.ivrconfig')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_calls', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
