# Generated by Django 5.1.4 on 2026-07-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiceai', '0005_eligibilitycall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EligibilityCall',
        ),
    ]
