# Generated by Django 5.2.4 on 2026-01-19 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0015_app_hide_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('insurance_provider', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=50, unique=True)),
                ('provider', models.CharField(max_length=100)),
                ('fax_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apikey', models.ForeignKey(db_column='apikey', on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='modules.app', to_field='api_key')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurances',
                'db_table': 'insurance',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
