# Generated by Django 5.1.4 on 2026-07-19 04:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_avatar_user_mfa_enabled_user_mfa_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('MCP', 'MCP Server'), ('REST', 'REST API')], default='REST', max_length=8)),
                ('base_url', models.URLField(help_text='MCP server URL or REST base URL.')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Error')], default='DISCONNECTED', max_length=14)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_connectors', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='accounts.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
