# Generated by Django 5.2.4 on 2025-09-02 16:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_client_client_name'),
        ('modules', '0004_rename_agent_api_secretkeys_agent_api_secretkeyss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('count', models.IntegerField(default=1)),
                ('apikey', models.ForeignKey(db_column='apikey', on_delete=django.db.models.deletion.CASCADE, related_name='api_usages', to='modules.agent_api_secretkeyss', to_field='api_key')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usages', to='accounts.client')),
            ],
            options={
                'db_table': 'client_api_usage',
                'indexes': [models.Index(fields=['client', 'apikey', 'date'], name='client_api__client__36d998_idx')],
                'unique_together': {('client', 'apikey', 'date')},
            },
        ),
    ]
