# Generated by Django 5.2.4 on 2025-09-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0001_initial'),
        ('modules', '0004_rename_agent_api_secretkeys_agent_api_secretkeyss_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clientapiusage',
            name='client_api__client__36d998_idx',
        ),
        migrations.AlterUniqueTogether(
            name='clientapiusage',
            unique_together={('apikey', 'date')},
        ),
        migrations.AddIndex(
            model_name='clientapiusage',
            index=models.Index(fields=['apikey', 'date'], name='client_api__apikey_6a4f65_idx'),
        ),
        migrations.RemoveField(
            model_name='clientapiusage',
            name='client',
        ),
    ]
