# Generated by Django 5.2.4 on 2025-09-22 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_client_api_key'),
        ('middleware', '0002_remove_clientapiusage_client_api__client__36d998_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=50)),
                ('prompt', models.TextField()),
                ('response_text', models.TextField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='accounts.client')),
            ],
        ),
    ]
