# Generated by Django 5.2.4 on 2025-09-22 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0003_clientaiusage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientaiusage',
            table='client_ai_usage',
        ),
    ]
