# Generated by Django 5.2.4 on 2025-09-22 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0004_alter_clientaiusage_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaiusage',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='clientaiusage',
            name='response_text',
        ),
    ]
