# Generated by Django 5.2.4 on 2026-01-19 12:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practicesettings', '0001_initial'),
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encounter_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('place_of_service_code', models.CharField(blank=True, max_length=2)),
                ('encounter_from_date', models.DateField(blank=True, null=True)),
                ('encounter_through_date', models.DateField(blank=True, null=True)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('encounter_mode', models.CharField(blank=True, help_text='Office, Telehealth, Ambulance, Home, etc.', max_length=30)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, help_text='Payment amount collected at encounter level', max_digits=10)),
                ('service_date_from', models.DateField(blank=True, null=True)),
                ('service_date_to', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('reason_for_visit', models.TextField(blank=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('prior_authorization', models.CharField(blank=True, max_length=60)),
                ('do_not_bill', models.BooleanField(default=False)),
                ('do_not_send_electronically', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to Submit'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='draft', max_length=30)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hospitalized_from', models.DateField(blank=True, null=True)),
                ('hospitalized_to', models.DateField(blank=True, null=True)),
                ('submit_reason', models.CharField(blank=True, max_length=10)),
                ('payer_doc_control', models.CharField(blank=True, max_length=50)),
                ('claim_code_10d', models.CharField(blank=True, max_length=50)),
                ('additional_claim_info', models.TextField(blank=True)),
                ('eclaim_note_type', models.CharField(blank=True, max_length=50)),
                ('eclaim_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_app.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant_app.patient')),
                ('primary_insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_encounters', to='practicesettings.patientinsurance')),
                ('referring_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_encounters', to='tenant_app.patientprovider')),
                ('rendering_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rendered_encounters', to='tenant_app.patientprovider')),
                ('supervising_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_encounters', to='tenant_app.patientprovider')),
            ],
            options={
                'db_table': 'patient_encounter',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AmbulanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency', models.BooleanField(default=False)),
                ('patient_weight_lbs', models.PositiveIntegerField(blank=True, null=True)),
                ('transport_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('pickup_address', models.TextField(blank=True)),
                ('dropoff_address', models.TextField(blank=True)),
                ('transport_code', models.CharField(blank=True, max_length=10)),
                ('reason_code', models.CharField(blank=True, max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('round_trip_description', models.TextField(blank=True)),
                ('stretcher_purpose', models.TextField(blank=True)),
                ('certification_reasons', models.TextField(blank=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_detail', to='tenant_encounter.encounter')),
            ],
            options={
                'verbose_name_plural': 'Ambulance Details',
                'db_table': 'ambulance_details',
            },
        ),
        migrations.CreateModel(
            name='EncounterServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('procedure_code', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('modifiers', models.CharField(blank=True, max_length=255)),
                ('units', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_charge', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('diag_pointers', models.CharField(blank=True, max_length=255)),
                ('minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_concurrent', models.BooleanField(default=False)),
                ('tos_code', models.CharField(blank=True, max_length=5)),
                ('ndc_code', models.CharField(blank=True, max_length=30)),
                ('reference_code', models.CharField(blank=True, max_length=30)),
                ('line_note', models.TextField(blank=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='tenant_encounter.encounter')),
                ('rendering_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_line_provider', to='tenant_app.patientprovider')),
            ],
            options={
                'db_table': 'encounter_serviceline',
                'ordering': ['date_from', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Main Office, Downtown Clinic', max_length=150)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('fax', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('place_of_service_code', models.CharField(blank=True, help_text='CMS Place of Service code (e.g. 11=Office, 02=Telehealth)', max_length=2)),
                ('timezone', models.CharField(default='America/New_York', help_text='IANA timezone name', max_length=50)),
                ('google_place_id', models.CharField(blank=True, help_text='Google Places API Place ID', max_length=100, null=True)),
                ('allow_appointment_reminders', models.BooleanField(default=True, verbose_name='Allow appointment reminders for this location')),
                ('include_address_in_reminders', models.BooleanField(default=True, verbose_name='Include address in appointment reminder notifications')),
                ('display_on_scheduling_page', models.BooleanField(default=True, verbose_name='Display location on practice scheduling page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='practicesettings.practiceinformation')),
            ],
            options={
                'verbose_name': 'Service Location',
                'verbose_name_plural': 'Service Locations',
                'db_table': 'service_location',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EncounterDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_code', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='tenant_encounter.encounter')),
            ],
            options={
                'db_table': 'encounter_diagnosis',
                'ordering': ['order'],
                'unique_together': {('encounter', 'order')},
            },
        ),
    ]
