# Generated by Django 5.2.4 on 2026-01-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_encounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounterserviceline',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
    ]
