# Generated by Django 5.2.4 on 2026-01-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_encounter', '0002_encounterserviceline_is_voided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounterserviceline',
            name='is_voided',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
