# Generated by Django 5.2.4 on 2026-01-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_encounter', '0003_alter_encounterserviceline_is_voided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to Submit'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('not_started', 'Not Started')], default='draft', max_length=30),
        ),
    ]
