# Generated by Django 5.1.15 on 2026-01-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_encounter', '0004_alter_encounter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='is_appt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
