# Generated by Django 5.2.4 on 2026-01-19 12:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('batch_no', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('insurance', 'Insurance'), ('patient', 'Patient'), ('adjustment', 'Adjustment'), ('refund', 'Refund')], max_length=50, null=True)),
                ('carc_code', models.CharField(blank=True, max_length=10, null=True)),
                ('rarc_code', models.CharField(blank=True, max_length=10, null=True)),
                ('entrye_type', models.CharField(blank=True, choices=[('charge', 'CHARGE'), ('adjustment', 'ADJUSTMENT'), ('payment', 'PAYMENT'), ('write_off', 'WRITE OFF'), ('takeback', 'TAKEBACK'), ('interest', 'INTEREST')], max_length=50, null=True)),
                ('insurance', models.CharField(blank=True, max_length=255, null=True)),
                ('adjudication_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('copay', 'Co-pay'), ('coinsurance', 'Co-insurance'), ('deductible', 'Deductible'), ('writeoff', 'Write Off'), ('payment', 'Payment')], max_length=50, null=True)),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('ach', 'ACH'), ('check', 'Check'), ('eft', 'EFT')], max_length=50, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_reversed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'payment_batch',
            },
        ),
        migrations.CreateModel(
            name='Payment_EOB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer', models.CharField(blank=True, max_length=255, null=True)),
                ('allowed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract_adj', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('second_adj', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deductible', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coinsurance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('copay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_eob',
            },
        ),
    ]
