# Generated by Django 5.2.4 on 2026-01-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_posting', '0001_initial'),
        ('tenant_claim_submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenant_claim_submission.claim'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='payment_posting.payment'),
        ),
        migrations.AddField(
            model_name='payment_eob',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eobs', to='tenant_claim_submission.claim'),
        ),
    ]
