# Generated by Django 5.2.4 on 2026-01-20 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_posting', '0002_initial'),
        ('tenant_claim_submission', '0001_initial'),
        ('tenant_encounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_eob',
            name='encounter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_encounter.encounter'),
        ),
        migrations.AddField(
            model_name='payment_eob',
            name='payment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_posting.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='claim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenant_claim_submission.claim'),
        ),
        migrations.AlterField(
            model_name='payment_eob',
            name='claim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eobs', to='tenant_claim_submission.claim'),
        ),
    ]
