# Generated by Django 5.2.4 on 2026-01-23 12:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_posting', '0003_payment_eob_encounter_id_payment_eob_payment_id_and_more'),
        ('tenant_claim_submission', '0002_sftpconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBatchSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='post_date',
            new_name='deposit_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='insurance',
            new_name='payer_name',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='adjudication_date',
            new_name='received_date',
        ),
        migrations.RenameField(
            model_name='payment_eob',
            old_name='second_adj',
            new_name='billed_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='carc_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='claim',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='entrye_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_reversed',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rarc_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reversal_of',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='source_type',
            field=models.CharField(blank=True, choices=[('ERA', 'ERA'), ('CHECK', 'Check'), ('ACH', 'ACH'), ('MANUAL', 'Manual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_POSTED', 'Partially Posted'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment_eob',
            name='claim_adjudication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment_eob',
            name='claim_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment_eob',
            name='coins_code',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_eob',
            name='copay_code',
            field=models.CharField(choices=[('none', 'None')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='payment_eob',
            name='patient_control_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment_eob',
            name='payer_claim_control_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment_eob',
            name='payer_claim_status_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment_eob',
            name='remark_codes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(help_text='Check number / ERA trace number', max_length=100),
        ),
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
        migrations.CreateModel(
            name='AdjustmentCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_code', models.CharField(choices=[('PR', 'Patient Responsibility'), ('CO', 'Contractual Obligation'), ('OA', 'Other Adjustment'), ('PI', 'Payer Initiated')], max_length=2)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['group_code', 'code'], name='payment_pos_group_c_23008a_idx')],
                'unique_together': {('group_code', 'code')},
            },
        ),
        migrations.AddField(
            model_name='payment_eob',
            name='adj_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payment_posting.adjustmentcode'),
        ),
        migrations.CreateModel(
            name='Payment_EOB_Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_posting.adjustmentcode')),
                ('eob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payment_posting.payment_eob')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_EOB_Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_line_number', models.IntegerField()),
                ('procedure_code', models.CharField(max_length=20)),
                ('line_charge_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_allowed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('remark_codes', models.JSONField(blank=True, null=True)),
                ('eob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payment_posting.payment_eob')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('PLB', 'PLB Adjustment'), ('REVERSAL', 'PLB Reversal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plb_reason_code', models.CharField(max_length=10)),
                ('plb_identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('posting_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_ledger_entries', to='payment_posting.payment')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_line_id', models.UUIDField(blank=True, null=True)),
                ('entry_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('ADJUSTMENT', 'Adjustment'), ('REVERSAL', 'Reversal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('responsibility_type', models.CharField(choices=[('PAYER', 'Payer'), ('PATIENT', 'Patient')], max_length=10)),
                ('source', models.CharField(default='ERA', max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('posting_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjustment_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_posting.adjustmentcode')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payment_posting.payment')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='tenant_claim_submission.claim')),
            ],
            options={
                'indexes': [models.Index(fields=['claim'], name='payment_pos_claim_i_7e97be_idx'), models.Index(fields=['batch'], name='payment_pos_batch_i_c7b76a_idx'), models.Index(fields=['entry_type'], name='payment_pos_entry_t_7ce95c_idx')],
            },
        ),
    ]
