# Generated by Django 5.2.4 on 2026-01-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_posting', '0004_paymentbatchsequence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_eob',
            name='coins_code',
        ),
        migrations.RemoveField(
            model_name='payment_eob',
            name='copay_code',
        ),
        migrations.AddField(
            model_name='payment_eob',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment_eob',
            name='procedure_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment_eob',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment_eob',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment_eob',
            name='units',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='Payment_EOB_Line',
        ),
    ]
