# Generated by Django 5.1.15 on 2026-01-26 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_posting', '0005_remove_payment_eob_coins_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentledger',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentledger',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payment_posting.payment'),
        ),
    ]
