# Generated by Django 5.1.15 on 2026-01-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_posting', '0006_paymentledger_notes_alter_paymentledger_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentledger',
            name='entry_type',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('ADJUSTMENT', 'Adjustment'), ('REVERSAL', 'Reversal'), ('CLAIMS', 'Claims')], max_length=20),
        ),
    ]
