# Generated by Django 5.1.15 on 2026-01-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_posting', '0007_alter_paymentledger_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentledger',
            name='adj_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
