# Generated by Django 5.1.15 on 2026-01-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_posting', '0008_paymentledger_adj_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_eob',
            name='adj_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
