# Generated by Django 5.1.15 on 2026-01-29 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_posting', '0009_payment_eob_adj_amount'),
        ('tenant_app', '0002_alter_appointment_type'),
        ('tenant_claim_submission', '0005_rename_total_charge_claim_allowed_claim_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentledger',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_ledger', to='tenant_app.patient'),
        ),
        migrations.AlterField(
            model_name='paymentledger',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='tenant_claim_submission.claim'),
        ),
    ]
