# Generated by Django 5.1.15 on 2026-02-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_posting', '0010_paymentledger_patient_alter_paymentledger_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentledger',
            name='entry_type',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('ADJUSTMENT', 'Adjustment'), ('REVERSAL', 'Reversal'), ('CLAIMS', 'Claims'), ('CHARGE', 'Charge')], max_length=20),
        ),
    ]
