# Generated by Django 5.1.6 on 2026-02-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_posting', '0011_alter_paymentledger_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='source_type',
            field=models.CharField(blank=True, choices=[('EFT', 'eft'), ('CHECK', 'check'), ('CASH', 'cash'), ('CARD', 'card')], max_length=20, null=True),
        ),
    ]
