# Generated by Django 5.1.6 on 2026-02-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_posting', '0012_alter_payment_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='source_type',
            field=models.CharField(blank=True, choices=[('eft', 'EFT'), ('check', 'Check'), ('cash', 'Cash'), ('card', 'Card')], max_length=20, null=True),
        ),
    ]
