# Generated by Django 5.2.4 on 2025-09-01 06:24

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('apikey', models.ForeignKey(db_column='apikey', on_delete=django.db.models.deletion.CASCADE, to='modules.app', to_field='api_key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_task',
                'indexes': [models.Index(fields=['apikey'], name='agent_task_apikey_62bc7b_idx'), models.Index(fields=['status'], name='agent_task_status_01ad98_idx'), models.Index(fields=['created_at'], name='agent_task_created_16aae5_idx'), django.contrib.postgres.indexes.GinIndex(fields=['data'], name='agenttask_data_gin', opclasses=['jsonb_path_ops'])],
            },
        ),
    ]
