# Generated by Django 5.2.4 on 2025-08-31 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # NOTE: `user` is already created by 0001_initial's CreateModel on a fresh
        # database, so adding the column again fails ("column user_id already exists").
        # Keep the migration-state bookkeeping but skip the redundant DB operation.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='agenttask',
                    name='user',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            database_operations=[],
        ),
    ]
