# Generated by Django 5.2.4 on 2025-09-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsapp', '0002_alter_agenttask_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agenttask',
            name='agent_task_apikey_62bc7b_idx',
        ),
        migrations.RemoveIndex(
            model_name='agenttask',
            name='agent_task_status_01ad98_idx',
        ),
        migrations.RemoveIndex(
            model_name='agenttask',
            name='agent_task_created_16aae5_idx',
        ),
        migrations.RemoveIndex(
            model_name='agenttask',
            name='agenttask_data_gin',
        ),
        migrations.AddField(
            model_name='agenttask',
            name='current_retry',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
