# Generated by Django 5.2.4 on 2025-10-17 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_client_api_key'),
        ('agentsapp', '0003_remove_agenttask_agent_task_apikey_62bc7b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField()),
                ('questions', models.JSONField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
    ]
