# Generated by Django 5.2.4 on 2025-10-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsapp', '0004_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('NEEDS-ATTENTION', 'Needs Attention')], default='NEW', max_length=50),
        ),
    ]
