# Generated by Django 5.2.4 on 2025-11-28 06:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsapp', '0005_alter_agenttask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
