# Generated by Django 5.1.15 on 2025-12-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentsapp', '0002_agenttask_user'),
        ('agentsapp', '0006_alter_agenttask_created_at'),
    ]

    operations = [
    ]
