# Generated by Django 5.1.15 on 2025-12-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentsapp', '0007_alter_agenttask_user'),
        ('agentsapp', '0008_alter_agenttask_user'),
    ]

    operations = [
    ]
