# Generated by Django 5.2.4 on 2026-02-25 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0030_alter_telehealthguestaccesstoken_max_access_count'),
        ('agentsapp', '0009_merge_20251211_0700'),
        ('modules', '0015_app_hide_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLifeCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retry_attempts', models.PositiveIntegerField(default=0)),
                ('retry_delay', models.PositiveIntegerField(default=0)),
                ('session_mode', models.CharField(choices=[('Stateless', 'Stateless'), ('Stateful', 'Stateful')], default='Stateless', max_length=50)),
                ('session_timeout', models.PositiveIntegerField(default=0, help_text='Idle time in minutes (0 = never end)')),
                ('strategy', models.CharField(blank=True, max_length=100, null=True)),
                ('allowed_api_keys', models.JSONField(blank=True, default=list)),
                ('trigger_mode', models.JSONField(default=list)),
                ('forward_condition', models.JSONField(default=list)),
                ('forward_keys', models.JSONField(blank=True, default=dict)),
                ('forward_to', models.CharField(choices=[('Phone Number', 'Phone Number'), ('SIP URI', 'SIP URI'), ('Webhook', 'Webhook'), ('Queue', 'Queue')], default='Phone Number', max_length=30)),
                ('forward_data', models.JSONField(blank=True, default=list)),
                ('end_call_keys', models.JSONField(blank=True, default=dict)),
                ('uni_directional_calls', models.JSONField(blank=True, default=list)),
                ('bi_directional_calls', models.JSONField(blank=True, default=list)),
                ('recording', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_life_cycle',
            },
        ),
        migrations.CreateModel(
            name='AgentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_days', models.JSONField(blank=True, default=list)),
                ('weekend_support', models.BooleanField(default=False)),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version_number', models.CharField(max_length=20)),
                ('voice', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_type', models.CharField(choices=[('Conversation', 'Conversation'), ('Action', 'Action')], default='Conversation', max_length=50)),
                ('gemini_model', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Paused', 'Paused'), ('Testing', 'Testing')], default='Draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.app')),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_versions', to='accounts.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_versions', to=settings.AUTH_USER_MODEL)),
                ('life_cycle_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_life_cycle', to='voiceAI.agentlifecycle')),
            ],
            options={
                'db_table': 'agent_version',
            },
        ),
        migrations.CreateModel(
            name='AgentScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='script', to='voiceAI.agentversion')),
            ],
            options={
                'db_table': 'agent_script',
            },
        ),
        migrations.CreateModel(
            name='ConfigJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_json', to='modules.app')),
            ],
            options={
                'db_table': 'config_json',
            },
        ),
        migrations.CreateModel(
            name='ConversationProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_data', models.TextField(blank=True, null=True)),
                ('input_json', models.JSONField(blank=True, default=list)),
                ('output_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_processes_app', to='modules.app')),
                ('app_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='voiceAI.agentversion')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_process', to='voiceAI.configjson')),
            ],
            options={
                'db_table': 'conversation_process',
            },
        ),
        migrations.CreateModel(
            name='TelephonySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_enabled', models.BooleanField(default=True)),
                ('outbound_enabled', models.BooleanField(default=False)),
                ('transport_type', models.CharField(choices=[('PSTN', 'PSTN'), ('WebRTC', 'WebRTC')], default='PSTN', max_length=10)),
                ('call_timeout', models.PositiveIntegerField(default=30)),
                ('call_recording', models.BooleanField(default=True)),
                ('max_concurrent_calls', models.PositiveIntegerField(default=50)),
                ('max_inbound_ring_duration', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='accounts.client')),
            ],
            options={
                'db_table': 'telephony_settings',
            },
        ),
        migrations.CreateModel(
            name='MobileNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('twilio_sid', models.CharField(max_length=100, null=True)),
                ('bin_url', models.CharField(max_length=250, null=True)),
                ('twiml_bin_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('twiml_bin_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_numbers', to='accounts.client')),
                ('telephony_settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mobile_numbers', to='voiceAI.telephonysettings')),
            ],
            options={
                'db_table': 'mobile_numbers',
            },
        ),
        migrations.AddField(
            model_name='agentversion',
            name='Telephony_Settings_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Telephony_Settings', to='voiceAI.telephonysettings'),
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('from_number', models.CharField(blank=True, max_length=20, null=True)),
                ('to_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('voice', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('config_source', models.CharField(choices=[('API', 'API'), ('Default', 'Default')], default='Default', max_length=20)),
                ('recording_path', models.TextField(blank=True, null=True)),
                ('transcript_path', models.TextField(blank=True, null=True)),
                ('recording_s3_url', models.URLField(blank=True, max_length=500, null=True)),
                ('transcript_s3_url', models.URLField(blank=True, max_length=500, null=True)),
                ('call_log_s3_url', models.URLField(blank=True, max_length=500, null=True)),
                ('extracted_s3_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('transferred', 'Transferred')], db_index=True, default='in_progress', max_length=20)),
                ('call_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='agentsapp.agenttask')),
                ('agent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='voiceAI.agentversion')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='modules.app')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'call_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='call_logs_created_14858e_idx'), models.Index(fields=['to_number', '-created_at'], name='call_logs_to_numb_6ba5d2_idx'), models.Index(fields=['user', '-created_at'], name='call_logs_user_id_2050d5_idx'), models.Index(fields=['app', '-created_at'], name='call_logs_app_id_5358f5_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='agentversion',
            unique_together={('client_id', 'app', 'version_number')},
        ),
    ]
