# Generated by Django 5.2.4 on 2026-02-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceAI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentversion',
            name='background_audio',
            field=models.CharField(choices=[('none', 'None'), ('office_ambience', 'Office ambience')], default='none', max_length=32),
        ),
    ]
