# Generated by Django 5.1.6 on 2026-03-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceAI', '0002_agentversion_background_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentversion',
            name='voice_type',
            field=models.CharField(choices=[('Real Time', 'Real Time'), ('STT-TTS', 'STT-TTS')], default='Real Time', max_length=50),
        ),
    ]
