# Generated by Django 5.1.6 on 2026-03-03 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_client_number_limit'),
        ('voiceAI', '0003_agentversion_voice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='configjson',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_json', to='accounts.client'),
        ),
    ]
