# Generated by Django 5.1.6 on 2026-06-30 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_client_allowed_ips'),
        ('modules', '0015_app_hide_app'),
        ('voiceAI', '0004_configjson_client'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configjson',
            unique_together={('app', 'client')},
        ),
    ]
