# Generated by Django 5.2.4 on 2025-10-21 11:32

import adminapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=adminapp.models.upload_to_faq)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=adminapp.models.upload_to_faq)),
                ('txt_file', models.FileField(blank=True, null=True, upload_to=adminapp.models.upload_to_faq)),
                ('json_file', models.FileField(blank=True, null=True, upload_to=adminapp.models.upload_to_faq)),
                ('py_file', models.FileField(blank=True, null=True, upload_to=adminapp.models.upload_to_faq)),
            ],
            options={
                'db_table': 'faqs',
            },
        ),
    ]
