# Generated by Django 5.2.4 on 2025-10-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='json_file',
            field=models.FileField(blank=True, null=True, upload_to='faq/jsons'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='faq/pdfs'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='py_file',
            field=models.FileField(blank=True, null=True, upload_to='faq/py_files'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='txt_file',
            field=models.FileField(blank=True, null=True, upload_to='faq/txts'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='faq/videos'),
        ),
    ]
