# Generated by Django 5.2.4 on 2025-10-21 13:18

import adminapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_faq_json_file_alter_faq_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='json_file',
            field=models.FileField(blank=True, null=True, upload_to=adminapp.models.upload_json),
        ),
        migrations.AlterField(
            model_name='faq',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=adminapp.models.upload_pdf),
        ),
        migrations.AlterField(
            model_name='faq',
            name='py_file',
            field=models.FileField(blank=True, null=True, upload_to=adminapp.models.upload_py),
        ),
        migrations.AlterField(
            model_name='faq',
            name='txt_file',
            field=models.FileField(blank=True, null=True, upload_to=adminapp.models.upload_txt),
        ),
        migrations.AlterField(
            model_name='faq',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=adminapp.models.upload_video),
        ),
    ]
