# Generated by Django 5.2.4 on 2025-11-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_faq_json_file_alter_faq_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
