# Generated by Django 5.1.4 on 2026-07-21 01:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_memberships_alter_user_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiles', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='accounts.tenant')),
            ],
        ),
    ]
