# Generated by Django 5.1.4 on 2026-07-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardconfig',
            name='pending',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
