# Generated by Django 5.2.4 on 2025-09-17 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_client_license_tier'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureCostEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('DEV', 'Development'), ('PROD', 'Production')], max_length=10, null=True)),
                ('disk_name', models.CharField(max_length=255)),
                ('disk_size_gb', models.PositiveIntegerField()),
                ('disk_type', models.CharField(max_length=50)),
                ('vm_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disk_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ip_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField()),
                ('tags', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azure_costs', to='accounts.client')),
            ],
            options={
                'db_table': 'azure_cost_entries',
            },
        ),
    ]
