# Generated by Django 5.2.4 on 2025-09-19 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_logo'),
        ('billing', '0002_azurecostentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('DEV', 'Development'), ('PROD', 'Production')], max_length=10, null=True)),
                ('disk_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('disk_size_gb', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('disk_type', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azure_machines', to='accounts.client')),
            ],
            options={
                'db_table': 'azure_machines',
                'ordering': ['client_id', 'tag'],
            },
        ),
        migrations.CreateModel(
            name='AzureBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disk_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ip_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='billing.azuremachine')),
            ],
            options={
                'db_table': 'azure_billing',
                'unique_together': {('machine', 'month')},
            },
        ),
        migrations.DeleteModel(
            name='AzureCostEntry',
        ),
    ]
