# Generated by Django 5.2.4 on 2025-11-25 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0023_summaryreportalert_schedule_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinutesOfMeetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('transcription_file', models.FileField(blank=True, null=True, upload_to='minutes_of_meetings/')),
                ('output', models.TextField(help_text='Generated Minutes of Meeting text')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes_of_meetings', to='accounts.client')),
            ],
        ),
    ]
