# Generated by Django 5.2.4 on 2025-11-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutesofmeetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutesofmeetings',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='minutes_of_meetings/output/'),
        ),
    ]
