# Generated by Django 5.2.4 on 2025-11-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutesofmeetings', '0002_minutesofmeetings_output_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutesofmeetings',
            name='transcription_file',
            field=models.FileField(blank=True, null=True, upload_to='minutes_of_meetings/input/'),
        ),
    ]
