# Generated by Django 5.2.4 on 2025-11-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_configuration', '0001_initial'),
        ('modules', '0015_app_hide_app'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentconfiguration',
            unique_together={('app', 'agent_name')},
        ),
    ]
