# Generated by Django 5.2.4 on 2025-11-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_configuration', '0002_alter_agentconfiguration_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconfiguration',
            name='role',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
