# Generated by Django 5.2.4 on 2025-11-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_configuration', '0003_alter_agentconfiguration_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconfiguration',
            name='agent_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='agentconfiguration',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
