# Generated by Django 5.2.4 on 2026-01-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practicesettings', '0001_initial'),
        ('tenant_encounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerscheduleblock',
            name='service_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_encounter.servicelocation'),
        ),
        migrations.AlterUniqueTogether(
            name='servicecode',
            unique_together={('name', 'procedures')},
        ),
        migrations.AddField(
            model_name='staffdailyschedule',
            name='staff_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='practicesettings.staffschedule'),
        ),
        migrations.AddField(
            model_name='stafftimeoff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='practicesettings.staffschedule'),
        ),
        migrations.AddField(
            model_name='visitreason',
            name='service',
            field=models.ForeignKey(help_text='Linked service code', on_delete=django.db.models.deletion.CASCADE, related_name='visit_reasons', to='practicesettings.servicecode'),
        ),
        migrations.AddConstraint(
            model_name='insuranceplan',
            constraint=models.UniqueConstraint(fields=('insurance_company', 'plan_name'), name='unique_plan_per_insurance_company'),
        ),
        migrations.AlterUniqueTogether(
            name='patientinsurance',
            unique_together={('patient', 'priority')},
        ),
        migrations.AlterUniqueTogether(
            name='practiceschedulingsettings',
            unique_together={('patient_provider',)},
        ),
        migrations.AlterUniqueTogether(
            name='staffdailyschedule',
            unique_together={('staff_schedule', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='visitreason',
            unique_together={('name', 'service')},
        ),
    ]
