# Generated by Django 5.2.4 on 2026-01-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicesettings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feescheduleentry',
            options={'ordering': ['procedure_code'], 'verbose_name': 'Fee Schedule Entry', 'verbose_name_plural': 'Fee Schedule Entries'},
        ),
        migrations.RemoveIndex(
            model_name='feescheduleentry',
            name='practiceset_name_7610fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='feescheduleentry',
            name='practiceset_state_e1d9e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='feescheduleentry',
            name='practiceset_status_2b606d_idx',
        ),
        migrations.RenameField(
            model_name='feescheduleentry',
            old_name='apply_to_claims',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='feescheduleentry',
            old_name='description',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='allowed_icd_codes',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='apply_to_encounters',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='apply_to_self_pay',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='authorization_required',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='billing_category',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='charge_amount',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='code_type',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='contract_id',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='coverage_type',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='effective_end_date',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='effective_start_date',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='max_allowed_amount',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='network_type',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='payer_name',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='plan_name',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='pricing_method',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='schedule_type',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='state',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='units',
        ),
        migrations.RemoveField(
            model_name='feescheduleentry',
            name='version',
        ),
        migrations.AddField(
            model_name='feescheduleentry',
            name='limiting_charge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum limiting charge amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feescheduleentry',
            name='non_par_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Non-participating provider amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feescheduleentry',
            name='par_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Participating provider amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feescheduleentry',
            name='procedure_code',
            field=models.CharField(help_text='CPT / HCPCS code (e.g., 99213, G0283)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='feescheduleentry',
            index=models.Index(fields=['modifier'], name='practiceset_modifie_f624c8_idx'),
        ),
        migrations.AddIndex(
            model_name='feescheduleentry',
            index=models.Index(fields=['is_active'], name='practiceset_is_acti_3453c3_idx'),
        ),
    ]
