# Generated by Django 5.1.15 on 2026-01-29 13:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_app', '0002_alter_appointment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('payment_id', models.CharField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment_type', models.CharField(choices=[('Check', 'Check'), ('Cash', 'Cash'), ('Card', 'Card')], max_length=30)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('check_number', models.CharField(blank=True, max_length=40, null=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_app.appointment')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_app.patient')),
            ],
            options={
                'db_table': 'payment_data',
            },
        ),
    ]
